### ISSUE TITLE
Support Julia 1.4?

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#1061]
# Description

Should moving to Julia 1.4 be a v0.1.0 milestone?

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by vchuravy** [comment]
Are there any blockers? I think we only need to upgrade CI?

**Comment by charleskawczynski** [comment]
Yeah, although @jakebolewski said that there's a core dump in #1029, which would be nice to have in v0.1

**Comment by jakebolewski** [comment]
Julia 1.4 fixes pre-compilation issues for running the tests suite / tutorials on Windows as well:

[Windows build error](https://dev.azure.com/climate-machine/ClimateMachine.jl/_build/results?buildId=4284&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=e95a39fa-5cd2-5eb3-7a94-1fe6d1d1b7b0&l=156)

https://github.com/CliMA/ClimateMachine.jl/pull/1123#issuecomment-631226457

**Comment by jakebolewski** [comment]
Slurm CI has been moved to Julia 1.4:
https://github.com/CliMA/slurmci/pull/36

Unit tests are currently passing on Julia 1.4 as well (to be merged).
https://github.com/CliMA/ClimateMachine.jl/pull/1123

Last Todo is to update the docs to reflect Julia 1.4 as the default on dev.
