### ISSUE TITLE
Wrapping comments and markdown at 80 characters?

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#1063]
Since we are pretty hard on wrapping the code at 80 characters, should we ask that comments be wrapped at 80 characters as well.

For example, right now if you open in your editor or the browser [`risingbubble.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/457db8c05dd7a85569ce0373449c7edb666f5324/experiments/AtmosLES/risingbubble.jl) many of the comments go right out of the browser view).

I would advocate for similar wrapping on the markdown files in the docs if possible (so that if you are viewing them in an editor as opposed to the web they look nice); see for instance [`codingconventions.md`](https://raw.githubusercontent.com/CliMA/ClimateMachine.jl/457db8c05dd7a85569ce0373449c7edb666f5324/docs/src/CodingConventions.md)

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by blallen** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by thomasgibson** [comment]
I agree with this. Sometimes the line-breaking can be a bit hard to read, but having to adjust my editor just to read trailing lines of code is more annoying (personally for me)
