### ISSUE TITLE
Clima standard for PR (squash, etc.)

### ISSUE THREAD

**Issue by smarras79** [CliMA/ClimateMachine.jl#1074]
# Description

Since there is a specific way that PR should be done in clima, it would be good to have an exact list of instructions in the Wiki that everyone should follow. 

For example:
- if you made changes to file experiments/AtmosLES/helloworld.jl that you are ready to push:
step 1) run the formatter from $HOME_CLIMA:   
         `julia .dev/climaformat.jl experiments/AtmosLES/helloworld.jl`
step 2) 
        `git add experiments/AtmosLES/helloworld.jl`
step 3) 
        Squash now? maybe. If you need to squash then:
        3.1) 
         ` git log `---> this will return your current #hash 
        3.2) 
        `git rebase -i #hash`
...
etc.
Last step) `git push origin branch_name`

This is the idea, but with a bit more details to make the list a fail-safe approach to a PR that anyone new and contributing to the code can follow as a recipe without remembering things by memory. Let's always remember that not all those who program in the ClimateMachine are proficient computer scientists (or don't have time to search for the correct solution those few times that they have a few minutes to contribute to the code).

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by akshaysridhar** [comment]
We currently have this : https://clima.github.io/ClimateMachine.jl/latest/HowToGuides/Contributing/CONTRIBUTING/

Is there additional information you would like to see included in there ?

**Comment by smarras79** [comment]
> We currently have this : https://clima.github.io/ClimateMachine.jl/latest/HowToGuides/Contributing/CONTRIBUTING/
> 
> Is there additional information you would like to see included in there ?

That's good. I would make sure that the table of contents in the in "How-to-Guides" reflects the actual sections in the document. For example, `Contributing` is not shown. 
Thanks @akshaysridhar
