### ISSUE TITLE
Driver arguments in the docs?

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#1084]
I was just trying to quickly find the driver arguments in the docs and the only place I could find them was in the various experiments, for instance [Held-Suarez](https://clima.github.io/ClimateMachine.jl/latest/generated/experiments/AtmosGCM/heldsuarez/)

This seemed a bit odd to me, and not sure where a better place would be.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
Yeah, this was a bit of a stop-gap until we have something better. I think @kpamnany provided a mechanism for individual experiments to provide custom options, but as far as I know none of them currently use this.

**Comment by jkozdon** [comment]
> I think @kpamnany provided a mechanism for individual experiments to provide custom options, but as far as I know none of them currently use this

What I was getting at was the many (all?) of the arguments can also be used with the tutorials, if you for instance want VTK output. But I did not see this info anywhere else in the docs.

There is actually a dead link in the [rising bubble](https://clima.github.io/ClimateMachine.jl/latest/HowToGuides/Atmos/Model/risingbubble/) `How To Guide` to the [wiki](https://github.com/CliMA/ClimateMachine.jl/wiki/ClimateMachine-command-line-arguments) for this...

**Comment by kpamnany** [comment]
I'm working on this (and other) part of the documentation. Will improve.
