### ISSUE TITLE
Diagnostics - element interface handling

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimateMachine.jl#1092]
# Description

Currently `AtmosDefault` output regards element interfaces as separate nodes, such that two instances of the same physical coordinate / variable are logged (one from each adjacent element). 
To avoid confusion at the output level, this is perhaps best addressed at the Diagnostics module level. 

## Additional context
Example (choose an arbitrary `AtmosDefault` output `.nc` file and examine, for instance, the z coordinate)
```
julia> z[:]
15-element Array{Float64,1}:
    0.0
  143.8943038716762
  416.66666666666634
  689.4390294616572
----- (e.g. 833 appears 2x)
  833.3333333333322
  833.3333333333322
  977.2276372050085
 1250.0000000000002
```

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jkozdon** [comment]
@akshaysridhar: We talked about this on slack, but figured it was worth summarizing on the issue

You could project the solution to a continuous, piecewise polynomial. In 1-D this would just be averaging the values across the faces. In multi-D the averaging need to be done properly across element corners and edges; the connectivity information needed for this is not currently constructed in the code.

Also keep in mind that even if the solution is made continuous, the derivative will still be discontinuous.

If the multi-D polynomial is made continuous and you dump data in minimal storage, you will also need a map from global degree of freedom to element local degree of freedom (or dump the data still in DG storage, which would not get around the problem noted above).

In general, I think that any diagnostics should take into account the fact that we have a piecewise polynomial, not just nodal points. For instance if an average and moments are needed these should be computed with an integral approximation not just by averaging the points; I believe we currently use the integral approximation in the diagnostics.

**Comment by jkozdon** [comment]
> You could project the solution to a continuous, piecewise polynomial

By "project" I mean an LGL-approximation of the L2 projection ([eqn latex](https://www.codecogs.com/eqnedit.php?latex=%5Cint%20%5Cphi%20%28p%20-%20%5Chat%7Bp%7D%29%20%3D%200%5C%5C%20%5Cphi%2C%20%5Chat%7Bp%7D%20%5Cin%20%5Cmbox%7Bspace%20of%20continuous%2C%20piecewise%20polynomial%7D%5C%5C%20p%20%5Cin%20%5Cmbox%7Bspace%20of%20discontinous%2C%20piecewise%20polynomial%7D)):

![latex](https://latex.codecogs.com/gif.latex?%5Cint%20%5Cphi%20%28p%20-%20%5Chat%7Bp%7D%29%20%3D%200%5C%5C%20%5Cphi%2C%20%5Chat%7Bp%7D%20%5Cin%20%5Cmbox%7Bspace%20of%20continuous%2C%20piecewise%20polynomial%7D%5C%5C%20p%20%5Cin%20%5Cmbox%7Bspace%20of%20discontinous%2C%20piecewise%20polynomial%7D)

> In 1-D this would just be averaging the values across the faces

Actually I think that this isn't quite correct, I believe that you also need to account for the Jacobians.

**Comment by jkozdon** [comment]
Some thought might also be needed to where the aliasing of nonlinear functions should occur (e.g., make continuous first or evaluate nonlinear functions first). Others with more experience might have thoughts / insight.

Also, I don't know if to get all the geometry correct you need to make continuous first then do slab averaging or whether you can make continuous after averaging; it's all linear so the order might not matter as long as the geometric terms are similarly slab averaged.

**Comment by kpamnany** [comment]
Per discussion on Slack, I will open a PR to allow using an interpolation configuration for `AtmosDefault` and `AtmosCore` which will close this issue.
