### ISSUE TITLE
@vars doesn't support splatting

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1101]
# Description

On this [branch](https://github.com/CliMA/ClimateMachine.jl/tree/ck/VariableTemplatesIssue), 

```julia
julia> include("test/Driver/single_stack_test.jl")
[ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
ERROR: LoadError: LoadError: Invalid expression
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] process_vars!(::Array{Any,1}, ::Array{Any,1}, ::Expr) at /Users/charliekawczynski/Dropbox/Caltech/work/dev/CliMA/CLIMA/src/Utilities/VariableTemplates/VariableTemplates.jl:65
 [3] @vars(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at /Users/charliekawczynski/Dropbox/Caltech/work/dev/CliMA/CLIMA/src/Utilities/VariableTemplates/VariableTemplates.jl:73
 [4] include at ./boot.jl:328 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1105
 [6] include(::Module, ::String) at ./Base.jl:31
 [7] include(::String) at ./client.jl:424
 [8] top-level scope at REPL[1]:1
in expression starting at /Users/charliekawczynski/Dropbox/Caltech/work/dev/CliMA/CLIMA/test/Driver/single_stack_test.jl:173
in expression starting at /Users/charliekawczynski/Dropbox/Caltech/work/dev/CliMA/CLIMA/test/Driver/single_stack_test.jl:172
```

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
I think it's more that it doesn't support splatting. Not sure that is really possible, given that it is a macro.

**Comment by simonbyrne** [comment]
Problem here: https://github.com/CliMA/ClimateMachine.jl/compare/CliMA:bdf1c96...CliMA:3a806de#diff-cadb308d0aa34673911530c099fa034cR172-R176

**Comment by charleskawczynski** [comment]
Just realized that there's some syntax issues with the input

**Comment by charleskawczynski** [comment]
Please hold on investigating, I'll update soon

**Comment by charleskawczynski** [comment]
Yeah, it seems that splatting is the problem

**Comment by charleskawczynski** [comment]
> Not sure that is really possible, given that it is a macro.

Is there any potential workaround here?

**Comment by jakebolewski** [comment]
construct the NamedTuple directly?

**Comment by charleskawczynski** [comment]
Makes sense
