### ISSUE TITLE
Revert #1086

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1111]
# Description

#1086 accidentally reverted several PRs, so this PR should probably be reverted as it included undoing several important documentation changes (several of which were for our v0.1 milestone).

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
We should probably hold all merges until this is resolved, to make it easy to revert.

Cc: @simonbyrne

**Comment by kpamnany** [comment]
This has stomped #1107, #1104, #1056, and #1029 AFAICT.

**Comment by vchuravy** [comment]
Working on fixing it.
