### ISSUE TITLE
`DumpStateAndAux` diagnostics output Unicode variable names

### ISSUE THREAD

**Issue by smarras79** [CliMA/ClimateMachine.jl#1128]
# Description

The use of symbols and greek letters in the NC variable names can be cause of complaint from users who have pre-defined tools to handle netcdf files. 

## Additional context

This emerged while reading the 3D netcdf files from my matlab netcdf tools. 
I can't read the netcdf variables using the matlab netcdf reader because it does not recognize the symbol `\theta` among its characters. 
This is not only an issue with matlab, but possibly with any standrard netcdf tool that the atmospheric and ocean communities have been using for many years (e.g. ncview, nco, ncargraphics, etc.). 
Visualization is something very personal and it is often difficult to convince someone to use new visualization tools they are not familiar with, especially when they have spent possibly writing their own plotting scripts based on existing tool.

I wanted to point this out and open this discussion. @akshaysridhar @kpamnany @bischtob @yairchn 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
We'd already agreed on this one -- no Unicode in diagnostic variable names.

The 'DumpStateAndAux' diagnostics don't follow this rule because... they're just dumping state and aux variables. I'll fix this by renaming them.

**Comment by kpamnany** [comment]
On second thoughts, this is very tricky because state and aux variables are different in different models. Any renaming will be hard-coded and need to be updated with each new model, model component, or extension. This will be very painful.

A generalized way to have non-Unicode equivalents might be better? But this will be hard to do also.

**Comment by christophernhill** [comment]
@smarras79 and @kpamnany do thee CF naming conventions ( http://cfconventions.org/standard-names.html ) help with some of this? Apparently now a version 72!

**Comment by smarras79** [comment]
> @smarras79 and @kpamnany do thee CF naming conventions ( http://cfconventions.org/standard-names.html ) help with some of this? Apparently now a version 72!

thanks for the link, @christophernhill . I'd like to use that type of naming (straight and clear) if all possible although I understand the issue that @kpamnany brought up about renaming things at this stage. But yes, the standard naming above would be ideal in my opinion.

**Comment by kpamnany** [comment]
To be clear: all other diagnostics groups have ['proper' names](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/DiagnosticVariables/) (for some definition of 'proper'). However, the 'DumpStateAndAux' diagnostics group directly outputs the variables as used in the model. Fixing this is going to be difficult.

**Comment by szy21** [comment]
We have a massive discussion about this earlier and here is my two cents. CF standard name is probably too long for model output, so we need a shorter name (e.g., see the AMIP column in CF naming conventions). We decided to abandon AMIP convention at the end because there are a lot of variables AMIP doesn't have, and their naming convention is not very intuitive either (e.g., hus for specific humidity). But I'm happy to switch to AMIP convention, if everyone is happy with it. I think we should make a decision sooner rather than later, since it seems a hassle to rename variables.

**Comment by kpamnany** [comment]
> it seems a hassle to rename variables

Not difficult for any diagnostics other than this group because this group simply dumps the names used by the main code.

**Comment by smarras79** [comment]
As @kpamnany mentioned above, since it was agreed to avoid unicode characters in diagnostics and output variables, it would be good to be consistent with it across all diagnostics. We don't necessarily need to use a standard naming; we can have our own naming as long unicode is avoided in full to prevent user complaints and questions later on.

Since the code is open source, we need to make sure that the users need support as little as possible, especially by requesting help related to their inability to handle certain things.

**Comment by kpamnany** [comment]
Reviewing this issue: I think the `Dump*` diagnostics groups are for debugging and therefore for them to output the Unicode names that ClimateMachine uses internally should be fine. #1880 makes it trivial to add your own `Dump*` diagnostics group with non-Unicode names, if required.

Unless folks disagree, I will close this shortly.

**Comment by szy21** [comment]
Here are x-z slices of TotalMoisture_BomexTendencies_1. The top and bottom figures are the first (t=0) and the second (t=600) timestep in the output.
From the driver, the total moisture tendency is ρ∂qt∂t - state.ρ * w_s * dot(k̂, diffusive.moisture.∇q_tot). I wonder why the two timesteps are very different. It seems that the first figure doesn't have the subsidence tendency while the second figure has it. @akshaysridhar Any thoughts?
![image](https://user-images.githubusercontent.com/11598433/106533779-96f6ba00-64a7-11eb-8bcb-0e3d143e16b5.png)
![image](https://user-images.githubusercontent.com/11598433/106533800-9eb65e80-64a7-11eb-981e-c17e67422394.png)
