### ISSUE TITLE
Use runmpi abstraction for all tests that depend on MPI 

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimateMachine.jl#1168]
# Description

Move all the tests that use MPI (including those that call `ClimateMachine,init()`) to be run wrapped by `runmpi`

Ref: https://github.com/CliMA/ClimateMachine.jl/issues/1167#issuecomment-634987358

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
Then you can get rid of this:
https://github.com/CliMA/ClimateMachine.jl/blob/41ecd5fa701d3d124c4aa282d42ab2581d4d3011/test/Numerics/Mesh/runtests.jl#L15-L24
