### ISSUE TITLE
Add hook for `init_state_auxiliary!` similar to `update_auxiliary_state!`

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1174]
# Description

We'll need to offer a way to compute indefinite stack integrals at initialization-- and not at every timestep. This is needed to compute reference states that require numerical integration along the vertical element stack. So, we should add a hook to define `init_state_auxiliary!` which has access to entire MPIStateArray, similar to how `update_auxiliary_state!` calls `nodal_update_auxiliary_state!`.

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by blallen** [comment]
So you want to turn `init_state_auxiliary!` into a wrapper like `update_auxiliary_state!` where you can do operations across the full domain and then create a `nodal_init_state_auxiliary!` that acts on the individual nodal points to assign the output of those calculations?

**Comment by charleskawczynski** [comment]
Exactly

**Comment by charleskawczynski** [comment]
I think that this was effectively closed by #1421.
