### ISSUE TITLE
Add support to call functions (`min`, `max`, `sum`) along stack `up_stack(fun, ...)`

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1175]
# Description

We'll need to be able to compute things like `max(ϕ)` where `ϕ` is a variable along the vertical stack. So, we should implement some function (`up_stack(fun, ...)`, `down_stack(fun, ...)`) to apply along the vertical stack. It would also be nice to return the `z` location of such `min`/`max`.

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [x] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
Vertical element stack?

**Comment by charleskawczynski** [comment]
Yes

**Comment by charleskawczynski** [comment]
It should be applied per nodal stack (similar to `indefinite_stack_integral`)
