### ISSUE TITLE
Atmos GCM initial condition projection is inconsistent

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimateMachine.jl#1211]
# Description

When initializing the GCM with what should be a purely zonal velocity profile with zero meridional and vertical velocity components, the initial conditions shows nonzero meridional and vertical velocity components. This leads to initial conditions that are far from balanced flow conditions even when analytically balanced initial conditions are prescribed.

The initial flow field is set up like `state.ρu = ρ * SVector{3, FT}(-sin(λ)*u, cos(λ)*u, 0)`
in the Cartesian coordinate system (x, y, z). If this is projected onto a spherical coordinate system, the flow field should have only a zonal component. See section 1.4 [here](https://www.brown.edu/Departments/Engineering/Courses/En221/Notes/Polar_Coords/Polar_Coords.htm).

It is possible that I am confusing something :-) about the mesh, the warping, or the interpolation for the output, @skandalaCLIMA, @jkozdon, @mwarusz , @charleskawczynski .

## Steps to reproduce

1. Use [this](https://github.com/CliMA/ClimateMachine.jl/blob/tb/projection-problem/experiments/AtmosGCM/moist-baroclinic-wave.jl) experiment GCM setup to reproduce.

## Expected behavior

We need a way to consistently prescribe initial velocity profiles. Those are often zonal profiles with perturbations (such as in the DCMIP benchmarks).

## Screenshots

This figure shows the initial condition with a the expected zonal velocity profile for `u`, albeit with a nonzero `v` and `w` component.
![Screen Shot 2020-06-07 at 9 52 55 PM](https://user-images.githubusercontent.com/12664448/83994293-c9491b00-a90a-11ea-9c5c-b793e9b4b3b3.png)

## Environment and error messages

No message

# For CLIMA developers

- [ ] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by smarras79** [comment]
@bischtob are you using Float64 or Float32? You have a vertical velocity O(1e-5) which I would expect, with a warping, if you are in single precision. However, if you are using Float64 then yes, the issue is major.

**Comment by bischtob** [comment]
It's `Float64` :(.
