### ISSUE TITLE
Remove `try`/`catch` from `EveryXWallTimeSeconds`

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimateMachine.jl#1212]
# Description

This appears to be swallowing errors and causing problems

Apparently it is for optional initialization.

@jkozdon on Slack:

> Maybe change the struct to have an init function:
> ```
> struct EveryXWallTimeSeconds
>     "time of the last callback"
>     lastcbtime_ns::Array{UInt64}
>     "time between callbacks"
>     Δtime::Real
>     "MPI communicator"
>     mpicomm
>     "function to execute for callback"
>     func::Function
>     "function to call to initialize the callback"
>     init::Function
>     function EveryXWallTimeSeconds(func, Δtime, mpicomm; init=()->nothing)
>         lastcbtime_ns = [time_ns()]
>         new(lastcbtime_ns, Δtime, mpicomm, func, init)
>     end
> end
> ```
> 

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by kpamnany** [comment]
This just gave me quite a headache, figuring out diagnostics initialization. I'll open a PR to fix this but... why does initialization need to be called within a try-catch?

**Comment by jakebolewski** [comment]
I think it's no-op fall through behavior if undefined, but this would be clearer just specifying the two phases separately with explicit fall through
