### ISSUE TITLE
Simplify debugging initial conditions / experiment configurations

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1213]
# Description

Debugging any sort of PDE solution almost always relies on testing several things in a specific order. For us, this procedure looks as follows:

 1. Verify `init_state_auxiliary!` (should rely on nothing).
 2. Verify `init_state_conservative!` (relies on the correctness of `init_state_auxiliary!`).
 3. Verify that the solution does not have NaNs after 1 timestep (relies on the correctness of `init_state_auxiliary!`, `init_state_auxiliary!`, `update_auxiliary_state!`, and `dostep!`).
 4. Verify that the solution does not have NaNs after multiple timesteps (relies on the correctness of `init_state_auxiliary!`, `init_state_auxiliary!`, `update_auxiliary_state!`, `dostep!`, and potentially callbacks).

After step 4, typically one has to start looking at stability, which requires a whole other set of debugging strategies/tools.

Right now, we cannot easily do several of these steps because of the current solver configuration. Adding a flag, `export_init_aux` to [SolverConfiguration](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/solver_configs.jl#L75), and exporting a VTK/JLD2 file (for visualization) [here](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/solver_configs.jl#L109) and [here](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/solver_configs.jl#L133) would significantly help decoupling the first two steps. However, we'd need to incorporate diagnostics somehow. IMO, this is currently a severe debugging bottleneck because both the initial aux state _and_ the initial conservative state must be defined correctly in order to visualize, and they're entangled via Thermodynamic functions.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by christophernhill** [comment]
@charleskawczynski etc.... a couple of vaguely related things, in case they are useful? None of them are as polished as Diagnostics viz, so not sure where they are going to end up.....

1. there is a little gist here 

https://gist.github.com/christophernhill/9d176cb0f2ebc9fe9361b03dc6512012 

that may also be useful in this context. It can produce crude column and slice plots on raw fields as code runs. Its pretty hacky at the moment (but is still proving useful) e.g. I haven't given too much careful thought to exactly how fully it could generalize to a cube sphere mesh, but most parts of it could definitely map with adding an extra transformation or two. Code is also aimed at single GPU for now, but that could also be improved. We have been using this as is, to help check ocean setups in a box e.g. 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3535328/84096676-85b8e480-a9d0-11ea-8ea5-bb5fb4b6a660.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3535328/84096723-9f5a2c00-a9d0-11ea-8065-f76d1d9a9a50.png">

one of the fun features of having a model in Julia is looking at stuff on the fly - at least for me! 
 

2. We were also thinking of extending the code here https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Diagnostics/Debug/StateCheck.jl a little to cover layer-by-layer stats and some exact DG integrals. That is also aimed at basic debugging/sanity checking.

**Comment by charleskawczynski** [comment]
> @charleskawczynski etc.... a couple of vaguely related things, in case they are useful? None of them are as polished as Diagnostics viz, so not sure where they are going to end up.....

Something like this seems like it could be super useful, however, this issue is a bit more focused on debugging from ICs to `dostep!`.

**Comment by charleskawczynski** [comment]
I was talking with @kpamnany earlier and I think it would be wise to move `init_state_auxiliary!` outside of `src` and making it the driver's responsibility to define. This would have some major benefits:

 - ICs are really driver dependent, and the init aux state must basically be in sync with `init_state_conservative!` (which are defined at the driver level).
 - We could more flexibly control how ICs are defined (between the conservative and aux states).

For example, we could have a generic `init_global_state!` method:

```
function global_init_state!(
    dg::DGModel,
    m::AtmosModel,
    Q::MPIStateArray,
    t::Real,
    elems::UnitRange,
)
    # Compute global quantities first, if needed.

    # Define ICS (we could even swap order if we wanted/needed):
    nodal_init_state_conservative!(held_suarez_nodal_init_state_conservative!, dg, m, Q, t, elems)
    nodal_init_state_auxiliary!(held_suarez_nodal_init_state_auxiliary!, dg, m, Q, t, elems)
end
```

And users can then overload `global_init_state!`, or simply specify the nodal versions in the driver/solver config. We did a similar thing with moving the `init_state_conservative!` outside of `src`, and I see no reason why we shouldn't do this with `init_state_auxiliary!`.

cc: @blallen , @jkozdon , @lcw, @simonbyrne

**Comment by blallen** [comment]
@charleskawczynski take a look at the separation between `model` and `problem` in `src/Ocean/HydrostaticBoussinesq`, `test/Ocean/ShallowWater`, and `test/Numerics/DGMethods/advection_diffusion`. This basically does the splitting you want without writing new functions.

Short version: `model` defines the PDE and `problem` defines the initial value problem, e.g. initial conditions, domain, and boundary conditions. For the `HBModel`, I define some default options in `src`, but they can be overwritten in the driver file or you can make a new `problem` in the driver file.

I think the change to a `global_init` that calls a `nodal_init` is still a good idea tho.
