### ISSUE TITLE
Move orientation.jl, turbulence.jl, hyperdiffusion.jl out of Atmos model

### ISSUE THREAD

**Issue by tapios** [CliMA/ClimateMachine.jl#1216]
# Description

There are several pieces of Atmos code that will be useful for other models (e.g., ocean, land). It would be good to move them out of the Atmos code and make them accessible to other models. 

# Additional context

Specifically,

- `orientation.jl` (latitude, longitude, altitude etc. should be generically useable by model components (ocean, land, sea ice)
- `turbulence.jl` and `hyperdiffusion.jl` would be useful for fluid components (ocean+atmosphere)

It would be nice to make these commonly accessible, e.g., as modules under `src/Common` or under `DGMethods` for `hyperdiffusion.jl`.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by charleskawczynski** [comment]
Still need to move turbulence and hyperdiffusion out

**Comment by charleskawczynski** [comment]
We still need to move `hyperdiffusion.jl`
