### ISSUE TITLE
Brick interpolation for dump_state_and_aux broken

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimateMachine.jl#1220]
# Description

https://github.com/CliMA/ClimateMachine.jl/blob/f2365411b5bc7f350cb0d2eeb1877d8d035941de/src/Numerics/Mesh/Interpolation.jl#L607 

Interfaces have changed and this is no longer a valid assignment.

## Steps to reproduce
Include a `dgngrp` diagnostic group with the `dump_state_and_aux` activated; current setup fails with `BrickInterpolation` configuration. due to undefined `dgngrp`. The fix is simply to remove the `dgngrp` from these lines I think. 
cc @skandalaCLIMA could you please confirm ?  

## Expected behavior

Expect a state-aux field output in netcdf format. 

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by kpamnany** [comment]
This is in a function I added -- moved it from 'DumpStateAndAux' actually, so it could be used by other diagnostics groups. Copy-paste error. :(
