### ISSUE TITLE
Diagnostic output for field perturbations

### ISSUE THREAD

**Issue by thomasgibson** [CliMA/ClimateMachine.jl#1225]
# Description

A standard benchmark for evaluating the output of atmospheric dynamical cores are field perturbations. These are fields that describe how far the flow has evolved from the background profile of the simulation; that is, `q - q_background`, where `q` is a prognostic (or diagnostic in the case of potential temperature) field and `q_background` is the corresponding background field.

Based on a discussion with @akshaysridhar, @kpamnany, and @charleskawczynski, this should be relatively straightforward to add.

# Additional context

Having this capability will help us better compare our output with other dynamical cores and analytic results when possible.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
Does this need to work on an interpolated grid or on the raw DG grid or on both?

As we don't currently have parallel NetCDF support, when we're running multiprocess we either have to write one file per process or gather the data to a single process and then write the data which is not a scalable solution especially as these are 3D fields. Simplest solution for now is one file per process.

**Comment by thomasgibson** [comment]
What are we currently doing for the prognostic variables? If we can treat the perturbation fields the same way we are dealing with the prognostic fields, that would be ideal I think. If the interpolated grid is the lat-lon grid (I'm not sure if I understand exactly what you mean by "interpolated grid"), then I think it's probably okay to not worry about that and _just_ use the raw DG grid (I'm assuming this is the field evaluated at nodal locations in the DG mesh?).

And for now, let's stick to the simplest solution.

**Comment by thomasgibson** [comment]
@bischtob Can you comment on this? Should we write out perturbations to the lat-lon grid? What is the best format for visualization in VizClima.jl?

**Comment by bischtob** [comment]
We should have perturbations on the lat lon grid. that is how we analyze things right now.

**Comment by akshaysridhar** [comment]
> What are we currently doing for the prognostic variables? If we can treat the perturbation fields the same way we are dealing with the prognostic fields, that would be ideal I think. If the interpolated grid is the lat-lon grid (I'm not sure if I understand exactly what you mean by "interpolated grid"), then I think it's probably okay to not worry about that and _just_ use the raw DG grid (I'm assuming this is the field evaluated at nodal locations in the DG mesh?).
> 
> And for now, let's stick to the simplest solution.

The interpolation grid is determined by the Mesh configuration. `CubedSphere`-> lat-long grid and `StackedBrick` -> Cartesian(x,y,z) coordinates. If your problem is defined on the sphere the interpolation module takes care of this. 
cc @skandalaCLIMA.

**Comment by kpamnany** [comment]
@akshaysridhar: please open another issue for the perturbations you want?
