### ISSUE TITLE
CUDA.jl

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#1228]
Since

- [`CUDAnative.jl`](https://github.com/JuliaGPU/CUDAnative.jl)
- [`CUDAdrv.jl`](https://github.com/JuliaGPU/CUDAdrv.jl)
- [`CuArrays.jl`](https://github.com/JuliaGPU/CuArrays.jl)
- [`CUDAapi.jl`](https://github.com/JuliaGPU/CUDAapi.jl)

Are now all depreciated should we be switcing to [`CUDA.jl`](https://github.com/JuliaGPU/CUDA.jl)?

Does this require making KA use `CUDA.jl` as well?

**Comment by vchuravy** [comment]
Also should wait for a CUDA.jl 1.0 tag which @maleadt wanted to do soon.

**Comment by jakebolewski** [comment]
Updated, `KernelAbstractions` made this change pretty painless which is nice.  Probably we would want to move device / back-end detection into kernel abstractions as well and then the number of changes would be minimal.

**Comment by jakebolewski** [comment]
Thanks @vchuravy for walking through some of the issues and spotting the specsig bug.
