### ISSUE TITLE
Add diagnostic variable attributes

### ISSUE THREAD

**Issue by kpamnany** [CliMA/ClimateMachine.jl#1230]
# Description

Every diagnostic variable listed [here](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/DiagnosticVariables/) needs to have an entry added in [this function](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Diagnostics/variables.jl#L25).

There will be common variables between GCM and LES. If there are any conflicts in long names or anything, we should discuss here.

We may want to split `setup_variables()` into a number of separate functions -- `setup_common_variables()`, `setup_les_default_variables()`, etc.?

# For CLIMA Developers

- [X] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
Yes, since they are all written with the variable name as key, so one will overwrite another. Need to think about a good solution.

**Comment by kpamnany** [comment]
For now, please just put in the different long names as comments in the existing variable definition.

**Comment by szy21** [comment]
@kpamnany this is wip (#1366). The list is quite long - do we want to split `setup_variables()` into separate functions now?

**Comment by kpamnany** [comment]
🤔 The trouble is that there are shared variables. I think just leave it in one function for now. I'm reworking all this anyway.
