### ISSUE TITLE
Regularly execute tutorials in reasonable time

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1233]
# Description

Currently, several tutorials are not executed because they [take too long](https://github.com/CliMA/ClimateMachine.jl/blob/master/docs/list_of_tutorials.jl#L65-L71). We should find a way to execute all of them regularly so that they don't fall out of sync.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by blallen** [comment]
I've found that reducing the number of elements is usually the easiest way to reduce the run time of a tutorial. For #1232, I was able to reduce the problem size by a factor of 40 (4 x 4 x 2.5 reduction in x,y,z) compared to the existing tests and make it so it only takes a couple of minutes to run on my laptop CPU. For the LES tests with periodic boundary conditions, this should be relatively easy to achieve.

**Comment by jakebolewski** [comment]
What is a reasonable time and how often do they have to run? 

I don't know if it's reasonable to run as often as the documentation jobs is run now.  Unfortunately that creates and issue as the built documentation needs the refs properly generated by the tutorials beforehand to statically check if they are consistent.

**Comment by jakebolewski** [comment]
If we give up that property and just embed some static html of the output into the docs then we could run / regenerate these periodically (~ once a day)

**Comment by smarras79** [comment]
@charleskawczynski can you define "too long"? 
Most 2D tests for the dycore takes up to a few minutes for the shortest and up to 30 minutes for the longest to complete on 1 GPU.

**Comment by charleskawczynski** [comment]
> What is a reasonable time and how often do they have to run?

I think a reasonable time is < 10 min per tutorial, ideally < 5 min. If the tutorials are not run elsewhere, it would be nice to run on every PR so that they don't go stale. I like the idea of reducing the resolution as @blallen suggested. That, and reducing `timeend` would really help (held suarez only takes ~8 min with its current parameters). We could leave comments for more realistic parameters.

> @charleskawczynski can you define "too long"? Most 2D tests for the dycore takes up to a few minutes for the shortest and up to 30 minutes for the longest to complete on 1 GPU.

We're not building docs with GPU resources, so they'll likely take longer compred to GPU runs. Also, several tutorials are not being run. At the moment, adding a few more tutorials makes the doc build take over 1.5 hrs.

**Comment by charleskawczynski** [comment]
I see no reason to regularly run tutorials that _are_ run elsewhere (e.g., slurm/GH runners).

@jakebolewski If we didn't run on every build, how would we update them when they are periodically updated? Would we just store/download artifacts of the html?

**Comment by charleskawczynski** [comment]
Several tutorials are removed from the docs in #1236, since they don't generate valid markdown and, when they do, the docs take too long.

**Comment by jakebolewski** [comment]
yeah I was thinking of just treating them as static html files (so no xref's to the api documentation).

**Comment by smarras79** [comment]
> > What is a reasonable time and how often do they have to run?
> 
> I think a reasonable time is < 10 min per tutorial, ideally < 5 min. If the tutorials are not run elsewhere, it would be nice to run on every PR so that they don't go stale. I like the idea of reducing the resolution as @blallen suggested. That, and reducing `timeend` would really help (held suarez only takes ~8 min with its current parameters). We could leave comments for more realistic parameters.
> 
> > @charleskawczynski can you define "too long"? Most 2D tests for the dycore takes up to a few minutes for the shortest and up to 30 minutes for the longest to complete on 1 GPU.
> 
> We're not building docs with GPU resources, so they'll likely take longer compred to GPU runs. Also, several tutorials are not being run. At the moment, adding a few more tutorials makes the doc build take over 1.5 hrs.

Reducing `timeend` is only meaningful if these tests are run to completion somewhere else. These are all tests that need to complete without breaking to be sure that the changes in a PR did not break them. They are very non-linear problems that may break far along a simulation so that a successful run to a  short timeend may hide a problem.

**Comment by charleskawczynski** [comment]
> Reducing timeend is only meaningful if these tests are run to completion somewhere else. These are all tests that need to complete without breaking to be sure that the changes in a PR did not break them. They are very non-linear problems that may break far along a simulation so that a successful run to a short timeend may hide a problem.

Agreed. At the moment many tutorials are being run in slurm. That said, I'm not sure if there are any tests in these tutorials, but that problem is orthogonal.

**Comment by jakebolewski** [comment]
Running tutorials in parallel is a start, we could generate output on beefier hardware:
#1250

**Comment by charleskawczynski** [comment]
@jakebolewski we can close this, right?

**Comment by jakebolewski** [comment]
Yes I think so, with the new setup tutorials take about 25 minutes and rendering the rest of the docs takes about 25 minutes.
