### ISSUE TITLE
Deprecated environment variables disregarded when using `ClimateMachine.cli()`

### ISSUE THREAD

**Issue by kpamnany** [CliMA/ClimateMachine.jl#1238]
# Description

When `cli()` calls `init()`, [this](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/Driver.jl#L349) test and [this](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/Driver.jl#L362) test always succeed because `cli()` calls `init()` with the [parsed keyword arguments](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/Driver.jl#L284) and those contain [defaults](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/Driver.jl#L102) for each setting that do not consider the deprecated environment variable names.

The outcome is that `CLIMATEMACHINE_GPU` and `CLIMATEMACHINE_OUTPUT_DIR` have already been deprecated for experiments.

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by jakebolewski** [comment]
I guess for boolean flags we need to provide a proper default value for the cli (like all the other flags), hopefully Argparse supports this.

this works correctly for `CLIMATEMACHINE_OUTPUT_DIR` though?

```
jake@jake-xps:~/clima/ClimateMachine.jl$ cat test.jl
using ClimateMachine
ClimateMachine.cli()

jake@jake-xps:~/clima/ClimateMachine.jl$ CLIMATEMACHINE_OUTPUT_DIR=foo julia --project test.jl
[ Info: Base.Iterators.Pairs{Symbol,Any,NTuple{17,Symbol},NamedTuple{(:fix_rng_seed, :checkpoint_at_end, :monitor_courant_numbers, :log_level, :integration_testing, :diagnostics, :checkpoint_dir, :disable_gpu, :monitor_timestep_duration, :vtk, :restart_from_num, :checkpoint_keep_all, :output_dir, :disable_custom_logger, :checkpoint, :checkpoint_keep_one, :show_updates),Tuple{Bool,Bool,String,String,Bool,String,String,Bool,String,String,Int64,Bool,String,Bool,String,Bool,String}}}(:fix_rng_seed => false,:checkpoint_at_end => false,:monitor_courant_numbers => "never",:log_level => "INFO",:integration_testing => false,:diagnostics => "never",:checkpoint_dir => "checkpoint",:disable_gpu => false,:monitor_timestep_duration => "never",:vtk => "never",:restart_from_num => -1,:checkpoint_keep_all => false,:output_dir => "foo",:disable_custom_logger => false,:checkpoint => "never",:checkpoint_keep_one => true,:show_updates => "60secs")
```

**Comment by kpamnany** [comment]
😕 I tried it with `CLIMATEMACHINE_GPU` on BOMEX and it didn't work...

**Comment by jakebolewski** [comment]
I assumed incorrectly that if the boolean flag argument is not provided on the cli, then argparse would not include the variable in the parsed args dictionary.  This doesn't seem to be the behavior so I'll have to see if there is a workaround.

**Comment by jakebolewski** [comment]
it seems like we can get the desired behavior with `:store_const`, with `constant = true` and `default = get_settings(...)` with one hack for CLIMATEMACHINE_GPU because it doesn't follow the other flag semantics.
