### ISSUE TITLE
Dumping Mass and Energy loss to file

### ISSUE THREAD

**Issue by smarras79** [CliMA/ClimateMachine.jl#1240]
# Description

Can we dump the mass and energy losses to either a txt or NC file that is independent of the rest of the diagnostics? 
The dumping should simply append the mass and energy loss at the current time step (or fallback call) to a file that looks like this:

time (s)   mass_loss   energy_loss
0          0           0
10      1e-14        1e-14
...
1000      1e-14        1e-14
...
10000     1e-14        1e-14

These are quantities that we should add to all of the initial benchmarking papers that are being written now but it will be good to have it regardless of the papers.

The loss is nothing else than:
![image](https://user-images.githubusercontent.com/46322845/84434862-c9913100-abfe-11ea-8499-fc688304c377.png)
(Disregard the bars which are from a paper with a different meaning for barred variables than we do)

Ideally, for each test we want to have a visual of something like these curves:

![image (1)](https://user-images.githubusercontent.com/46322845/84434879-d01fa880-abfe-11ea-997a-0367cb302b77.png)

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by akshaysridhar** [comment]
https://github.com/CliMA/ClimateMachine.jl/blob/44c45eb762b8dc4c5af091079f2d65c024cb8d27/experiments/AtmosLES/bomex.jl#L526 unifying this and #1239 should help address that
