### ISSUE TITLE
Creating a topography tutorial

### ISSUE THREAD

**Issue by smarras79** [CliMA/ClimateMachine.jl#1254]
# Description

From a meeting with @tapios and @akshaysridhar it arose that we don't have a specific tutorial to teach users how to add topography. A simple tutorial should be added to drive the user through the process.

To build this tutorial simply make a copy of the linear HS mountain wave test from open [PR 1163](https://github.com/CliMA/ClimateMachine.jl/pull/1163/), clean it up, and concentrate on the topography construction part of the tutorial. The initial condition can be the same of the linear HS test.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by akshaysridhar** [comment]
@smarras79 : This is a duplicate of #1253. Shall we delete one of these ?

**Comment by smarras79** [comment]
Sure, let me close mine. I hadn't realized you had opened it while we were at the meeting. Thanks
