### ISSUE TITLE
qt / GKS failures in doc build

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1261]
# Description

It looks like #1250 introduced some warnings related to `qt`/`GKS` in the doc build:

```
[ Info: executing notebook `bgmres.ipynb`
      From worker 3:	QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
      From worker 3:	qt.qpa.screen: QXcbConnection: Could not connect to display 
      From worker 3:	Could not connect to any X display.
      From worker 3:	connect: Connection refused
      From worker 3:	GKS: can't connect to GKS socket application
      From worker 3:	
      From worker 3:	GKS: Open failed in routine OPEN_WS
      From worker 3:	GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
      From worker 3:	QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
      From worker 3:	qt.qpa.screen: QXcbConnection: Could not connect to display 
      From worker 3:	Could not connect to any X display.
      From worker 3:	connect: Connection refused
      From worker 3:	GKS: can't connect to GKS socket application
      From worker 3:	
      From worker 3:	GKS: Open failed in routine OPEN_WS
      From worker 3:	GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
      From worker 3:	QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
      From worker 3:	qt.qpa.screen: QXcbConnection: Could not connect to display 
      From worker 3:	Could not connect to any X display.
      From worker 3:	connect: Connection refused
      From worker 3:	GKS: can't connect to GKS socket application
      From worker 3:	
      From worker 3:	GKS: Open failed in routine OPEN_WS
      From worker 3:	GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```

@jakebolewski I didn't closely look into `-get -qq` in [these changes](https://github.com/CliMA/ClimateMachine.jl/pull/1250/files#diff-654965a0f240efc62d1413a634170e97L27-R29). Might this be the issue?

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jakebolewski** [comment]
No that's just to not show any output upon apt-install if there are no errors.  I don't know what is going on with GR.jl here (which is the issue)

**Comment by jakebolewski** [comment]
Looks like we are hitting this:

https://github.com/jheinen/GR.jl/issues/172

**Comment by jakebolewski** [comment]
It seems the (partial) resolution to this is setting `GR.inline("png")` which should work for the tutorials?

**Comment by jakebolewski** [comment]
Are you seeing this locally or only on CI?  I cannot reproduce it on my (Linux) laptop.

**Comment by charleskawczynski** [comment]
On CI (I haven't checked locally yet). [Here](https://github.com/CliMA/ClimateMachine.jl/runs/780857975#step:6:43) is the first time I saw it.
