### ISSUE TITLE
Revert Thermo changes in #1273

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1274]
# Description

#1050 introduced bugs that resulted in CI passing when it should have been failing. So, changes that resulted in CI failing were reverted in #1273. We now need to properly revert #1273 without silently breaking CI. Items include:

 - [ ] Add the print statements back in and somehow test that non-convergence results in failures. @vchuravy I may need your help with configuring a unit test for this.
 - [ ] Add new relative humidity method
 - [ ] Add unit tests (e.g., `temperature_and_humidity_from_virtual_temperature`)

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by tapios** [comment]
Are there any conceptual issues I can help with? Or is it just coding issues?

**Comment by tapios** [comment]
Could you describe what the CI issues are? Reverting the thermodynamics changes is re-introducing crude approximations in the thermodynamics that we had replaced by more accurate relations. I’d rather avoid going back to inferior physics.

**Comment by tapios** [comment]
Thanks, @charleskawczynski. If you could isolate what fails, let's meet to go over this. I'm surprised that #1273 would affect saturation adjustment. There may be other issues (e.g., numerics).
