### ISSUE TITLE
Add 3rd-order Heun's Method as a SSPRK Solver

### ISSUE THREAD

**Issue by blallen** [CliMA/ClimateMachine.jl#1277]
# Description

@jm-c and I would like to have the following Butcher tableau implemented to use for our split-explicit method.

https://en.wikipedia.org/wiki/List_of_Runge%E2%80%93Kutta_methods#Heun's_third-order_method

@jkozdon, @thomasgibson, @fxgiraldo, can one of you do the conversion?

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jkozdon** [comment]
I outlined how to do it here: https://github.com/CliMA/ClimateMachine.jl/pull/1136#discussion_r436163769

**Comment by jm-c** [comment]
@jkozdon I am not sure that Heun's 3rd Order method fits into the current storage of SSPRK code. May be we will need to add it to
an other RK scheme code ? or write a 3-level storage RK scheme like Blum (62) paper for the clasical RK4 ?

**Comment by jkozdon** [comment]
@jkozdon<https://github.com/jkozdon> I am not sure that Heun's 3rd Order method fits into the current storage of SSPRK code. May be we will need to add it to an other RK scheme code ? or write a 3-level storage RK scheme like Blum (62) paper for the clasical RK4?

I’m fine with someone adding capability to handle standard butcher tableaus.
