### ISSUE TITLE
ClimateMachine needs method definition updates upon upgrade to WriteVTK v1.7.0

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimateMachine.jl#1282]
# Description

Ex. example method failure: https://gist.github.com/climabot/16717334848b5454bfe9fbfd12cafa79#file-out_10024760

Workaround is to pin at version 1.6.0

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jipolanco** [comment]
Hi, I just happened to bump into this issue, and I think I can help...

The [`MeshCell`](https://github.com/jipolanco/WriteVTK.jl/blob/master/src/gridtypes/unstructured/unstructured.jl#L37) type of WriteVTK was modified in 1.7 to support polygonal data files. It now has an additional `CellType` parameter which wasn't there before:

```julia
struct MeshCell{CellType, V <: Connectivity}
# ...
end
```

In [`writemesh`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/InputOutput/VTK/writemesh.jl#L43) you're allocating an array of `MeshCell`s by setting the type of the `V` parameter. The easy fix would be to prepend the `CellType` parameter. In your case you want `VTKCellTypes.VTKCellType` (which is the type of `VTKCellTypes.VTK_PIXEL`). Something like this should work:

```julia
M = MeshCell{VTKCellTypes.VTKCellType, Array{Int, 1}}
cells = Array{M, 1}(undef, Nsubcells * length(realelems))
```

Of course, this will break compatibility with older WriteVTK versions.

(Sorry for the breaking change, I didn't expect people to rely on the type parameters :-) ).

**Comment by simonbyrne** [comment]
Thanks @jipolanco, much appreciated!
