### ISSUE TITLE
--vtk and output/ creation

### ISSUE THREAD

**Issue by christophernhill** [CliMA/ClimateMachine.jl#1300]
Adding a quick note in case someone else runs into this....

The trigger for creating "output/" is having --vtk or --diagnostics set to something other than "never" on CLI (or in ENV). This can be a little confusing because you can request vtk to try and write from function calls in code e.g.

```
vtk_interval = ceil(Int64, timeout / solver_config.dt)
ClimateMachine.Settings.vtk = "$(vtk_interval)steps"
```

from ( https://github.com/CliMA/ClimateMachine.jl/blob/978bc60a5c9d03a240967e7e04733038010bec50/experiments/OceanBoxGCM/ocean_gyre.jl#L91 )

These lines in code no longer trigger the creation of output/, so unless a --vtk SOMETHING CLI option (or ENV) is given then an error occurs e.g.

```
  SystemError: opening file "output/ocean_gyre_mpirank0000_num0001.vtu": No such file or directory
```

(unless the directory output/ already exists).

**Comment by kpamnany** [comment]
As described [here](https://github.com/CliMA/ClimateMachine.jl/issues/1310#issuecomment-651946849), one should avoid directly writing into `ClimateMachine.Settings`. Instead use `ClimateMachine.init(vtk = "$(vtk_interval)ssecs")`. I'll add some more text [here](https://clima.github.io/ClimateMachine.jl/latest/GettingStarted/RunningClimateMachine/#Input-and-output-1) to clarify this -- will that be sufficient?
