### ISSUE TITLE
Atmospheric GCM Dycore Debugging

### ISSUE THREAD

**Issue by thomasgibson** [CliMA/ClimateMachine.jl#1306]
# Description

I am logging this issue to keep track of the progress on issues relating to the functionality of the GCM dycore. We should use this issue to centralize discussion on what the current problems are and identifying solutions.

Problems that people discover should be updated here. Related PRs that are focused on benchmarks/tests for the GCM dycore include: #1205, #1193

## Known issues

- Discrete balancing issues: Hydrostatic balance issues detailed in #1247, and a problem has been identified in the geopotential gradient (proposed fix in #1292)

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by thomasgibson** [comment]
@bischtob If you can add some of the VizClima plots you've saved and/or add more to the `Known Issues` section, please drop some stuff in. I will update this issue gradually as well.

**Comment by thomasgibson** [comment]
Update: the following run was performed using the domain setup:
```
┌ Info: Establishing Atmos GCM configuration for BaroclinicWave
│     precision        = Float64
│     polynomial order = 4
│     #horiz elems     = 20
│     #vert elems      = 5
│     domain height    = 3.00e+04 m
│     MPI ranks        = 1
│     min(Δ_horz)      = 61096.87 m
└     min(Δ_vert)      = 1036.04 m
```
and with an IMEX ARK solver `ARK2GiraldoKellyConstantinescu`. Key things about this run are the inclusion of the turbulence closure `SmagorinskyLilly{Float64}(0.21)`, no hyperdiffusion, and the `CuttoffFilter`. The simulation remains stable until after 6 days of simulation time. Lat-lon and lat-alt plots are shown at 561262.432 simulation seconds (about 6.5 days). There are the last visualizations I have before the run getting killed due to `NaN`s.
[latlon-6p5d.pdf](https://github.com/CliMA/ClimateMachine.jl/files/4858865/latlon-6p5d.pdf)
[latalt-6p5d.pdf](https://github.com/CliMA/ClimateMachine.jl/files/4858867/latalt-6p5d.pdf)

There appears to be noise in the vertical component of velocity that I suspect may be causing our problems. We should probably take a closer look at the SGS turbulence models.

**Comment by smarras79** [comment]
that's a step forward, right? At what point was it breaking before using this setup? 
Probably your dt is still too large and you pass your Courant value once the wave breaks and new gravity waves are generated. 
Also, if  the cutoff filter is nothing else than the Boyd filter, you may want to make it a bit stronger by tubing its coefficient. I don't think the issue now is the SGS model anymore. It seems purely numerical instability related.

**Comment by bischtob** [comment]
Running the setup with a hyperdiffusion time scale `3600s`, polynomial order `3`, element number `15 horz x 6 vert`, and exponential filter order `20`. As you can see below, there is strong imprinting at element edge in the middle of the atmosphere where the zonal flow is the fastest. Any thoughts?

![Screen Shot 2020-07-03 at 9 56 36 AM](https://user-images.githubusercontent.com/12664448/86487694-a2b4af00-bd13-11ea-8162-6bd484fa2f6e.png)
![Screen Shot 2020-07-03 at 9 56 22 AM](https://user-images.githubusercontent.com/12664448/86487699-a5af9f80-bd13-11ea-8a74-65e7a140e67f.png)

**Comment by fxgiraldo** [comment]
@bischtob @thomasgibson  how are these configurations different from the ones you guys showed me yesterday for a 20-day simulation?  Trying to understand the differences between these two runs.

**Comment by fxgiraldo** [comment]
> Update: the following run was performed using the domain setup:
> 
> ```
> ┌ Info: Establishing Atmos GCM configuration for BaroclinicWave
> │     precision        = Float64
> │     polynomial order = 4
> │     #horiz elems     = 20
> │     #vert elems      = 5
> │     domain height    = 3.00e+04 m
> │     MPI ranks        = 1
> │     min(Δ_horz)      = 61096.87 m
> └     min(Δ_vert)      = 1036.04 m
> ```
> 
> and with an IMEX ARK solver `ARK2GiraldoKellyConstantinescu` (dt = 3.46223e+01). Key things about this run are the inclusion of the turbulence closure `SmagorinskyLilly{Float64}(0.21)`, no hyperdiffusion, and the `CuttoffFilter`. The simulation remains stable until after 6 days of simulation time. Lat-lon and lat-alt plots are shown at 561262.432 simulation seconds (about 6.5 days). There are the last visualizations I have before the run getting killed due to `NaN`s. Here are the lat-long slices:
> [latlon-6p5d.pdf](https://github.com/CliMA/ClimateMachine.jl/files/4858865/latlon-6p5d.pdf)
> 
> And the lat-alt slices:
> [latalt-6p5d.pdf](https://github.com/CliMA/ClimateMachine.jl/files/4858867/latalt-6p5d.pdf)
> 
> There appears to be noise in the `v` and `w` components component of velocity that I suspect may be causing our problems. We should probably take a closer look at the SGS turbulence models.
> 
> The branch used to get these results: https://github.com/CliMA/ClimateMachine.jl/tree/thg/rebased-baroclinicwave

The results at day 6.5 look quite clean (except for the w-velocity; temperature looks good is the v-velocity too large? I assume the u-velocity is the perturbation from the initial flow. This might also be too large?). Out of curiosity, what happens with constant 2nd order diffusion?  This would be a way to diagnose if the issue is with the SGS.

**Comment by smarras79** [comment]
@thomasgibson @bischtob @fxgiraldo I am surprised to see what looks like grid imprinting in the 2D lat-lon plot of u, v, theta, vorticity, but not in the lat-z plots of the same quantities. Is there some interpolation causing that or is the grid imprinting an actual result of the model?

**Comment by fxgiraldo** [comment]
> @thomasgibson @bischtob @fxgiraldo I am surprised to see what looks like grid imprinting in the 2D lat-lon plot of u, v, theta, vorticity, but not in the lat-z plots of the same quantities. Is there some interpolation causing that or is the grid imprinting an actual result of the model?

@smarras79 good point.  @thomasgibson @bischtob, how are the latlon plots being produced?  They are surely different from the lat-alt plots.

**Comment by bischtob** [comment]
> @thomasgibson @bischtob @fxgiraldo I am surprised to see what looks like grid imprinting in the 2D lat-lon plot of u, v, theta, vorticity, but not in the lat-z plots of the same quantities. Is there some interpolation causing that or is the grid imprinting an actual result of the model?

@smarras79 , actually you can see it in the lat-z plots of u as well at the same height as the unphysical values of w appear in the lat-z plot of w. This problem is much reduced when taking a smaller time step. We use a max CFL in the model of 0.2 for these plots. When you use 0.1 it is much better.

**Comment by jkozdon** [comment]
> This problem is much reduced when taking a smaller time step. We use a max CFL in the model of 0.2 for these plots. When you use 0.1 it is much better.

@fxgiraldo could the fact that our filter is not idempotent be having an impact here? Should we be doing something like [Kanevsky, Alex, Mark H. Carpenter, and Jan S. Hesthaven. "Idempotent filtering in spectral and spectral element methods." Journal of Computational Physics 220, no. 1 (2006): 41-58.](https://doi.org/10.1016/j.jcp.2006.05.014)?
