### ISSUE TITLE
Add Boyd-Vandeven filter to dycore

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimateMachine.jl#1350]
# Description

It would be good to have the [Boyd-Vandeven](https://www.math.uh.edu/~hjm/june1995/p00267-p00276.pdf) filter in addition to the already existing filters.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [x] There is a timeline for when this feature can be implemented
- [x] The feature has been (or will be) implemented (Please link the PR)

**Comment by bischtob** [comment]
Created issue to keep track of development :)

**Comment by thomasgibson** [comment]
@slifer50 Has a branch with this set up, I am checking and testing it this week.
