### ISSUE TITLE
Separate the configuration from driver (e.g. BOMEX - LES v single stack)

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimateMachine.jl#1356]
- Ocean folks already have something similar...

**Comment by tapios** [comment]
What we want here is a separation of concerns, specifying separately, and in a composable way, 

- Configuration (e.g., LES, GCM, single-stack)
- Experiment details (initial conditions and top and bottom boundary conditions
- Parameters (both for planet and free parameters)

The driver should compose configuration, experiment details, and parameters into a model.

The purpose is for us to be able to run, e.g., LES and a single-stack configuration with the exact same forcing and boundary conditions (e.g., derived from GCM, such as the GCP runs). Prototyping this with BOMEX for a LES and single-stack (with EDMF parameterization) would be good.

**Comment by bischtob** [comment]
Does this only apply to planar geometries? Example, the Held-Suarez forcing is specific to the sphere (at least the way it is coded up now).

**Comment by tapios** [comment]
> Does this only apply to planar geometries? Example, the Held-Suarez forcing is specific to the sphere (at least the way it is coded up now).

Yes, it's not arbitrarily composable. HS is spherical as coded (but you could make it into a channel, for example, once we have a configuration for that).
