### ISSUE TITLE
LES experiments fail when specifying --vtk output

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimateMachine.jl#1376]
# Description

The LES experiments (e.g. bomex) fail when writing vtk with the error message `Prognostic not defined`. 

## Steps to reproduce

1. Pull the current master
2. Run bomex: mpirun julia --project experiments/AtmosLES/bomex.jl --diagnostics 60ssecs --vtk 60ssecs
3. The simulation fails at 60 simulated seconds

## Expected behavior

vtk files will be produced at 60 simulated seconds.

## Additional context

@akshaysridhar suggests this solution: Change [this line](https://github.com/CliMA/ClimateMachine.jl/blob/ec3fe492043ceb22c7a0b8280ea244a520294abd/src/Driver/Callbacks/Callbacks.jl#L17) to: `using ..BalanceLaws: vars_state, Prognostic, Auxiliary`. The simulation runs through with vtk output after making this change. However, the simulation fails at the last time step, with the error message `ERROR: LoadError: MethodError: no method matching -(::Nothing, ::Float32)`.

# For CLIMA developers

- [x] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by kpamnany** [comment]
The second problem is solved in #1335. I'll add the fix for the first one in that as well.
