### ISSUE TITLE
Remove `total_specific_enthalpy` from AtmosModel and update MMS tests

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1381]
# Description

We should probably call `total_specific_enthalpy` directly in thermo, rather than having a wrapper in the AtmosModel. To do this, we need to update the MMS tests, which currently set `total_specific_enthalpy` to zero.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by tapios** [comment]
Specifically, this MMS test (https://github.com/CliMA/ClimateMachine.jl/blob/master/test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl) uses `total_specific_enthalpy` and sets it to zero. This zeros out kinetic energy too, although the flow velocity is nonzero. I'm not sure this is intended, but it's dynamically inconsistent. The best I think would be to remove the overloaded `pressure`, `soundspeed`, and enthalpy calculations and use the defaults for the dry model.

**Comment by charleskawczynski** [comment]
This is tied to #1544, and I recently figured out a simple way to do this. Should be able to open a PR soon.

**Comment by charleskawczynski** [comment]
Closed by #1557
