### ISSUE TITLE
Comments on #1280 style changes 

### ISSUE THREAD

**Issue by christophernhill** [CliMA/ClimateMachine.jl#1389]
@charleskawczynski , @blallen, @kpamnany, @jkozdon, @thomasgibson and @simonbyrne  I have a couple of comments on #1280 (which as far as I can see is a purely cosmetic change but looks like it impacts pretty much every use of the NPS DG tools). I think you were all somewhat reviewers - albeit possibly unwittingly! 

1. as we are doing more with DG tool, these cosmetic changes potentially impact more people who may be in the midst of working with balance laws (which are kind of the heart of the DG tool) on branches/forks or elsewhere. This is potentially disruptive to peoples workflows - at least it was to mine! For example we are just starting work on some ocean channel setups that are testing new configurations, numerical ideas and performance optimizations. Each of those activities was broken by #1280. Having these break for cosmetic refactoring seems disruptive in a way that isn't obviously useful. 

2. I actually don't think #1280 in particular is obviously a slam-dunk improvement. Thats a little subjective, and probably if it had been the new way from day one then it would not have invited consideration. Nevertheless, it might be worth exploring for this sort of opinionated/subjective change that impacts peoples work letting the old interface coexist and then soliciting feedback and thoughts on which people prefer.

I feel at this stage we want to entrain key people to get enough hands evaluating overall model strengths and weaknesses and improving the models. Imposing refactoring changes like these will put some people off, which can impact progress.  

Going forward is there a way we could start being more wary about imposing new purely cosmetic changes with wide impact quite so unilaterally? For example by adding new interfaces alongside the working ones and allowing some time for more comprehensive review?

**Comment by simonbyrne** [comment]
Certainly nobody wishes to cause problems for other people working on the project and that this change caused problems is regrettable. However the PR was opened on June 23 and merged nearly a month later -- plenty of time for people to comment, and indeed many did (people from Caltech, MIT, and NPS had all reviewed it), so it wasn't a unilateral change.

Unfortunately this is probably going to continue to happen in future as we continue to refine and refactor the interfaces: I'm happy to allow backward compatibility if it's not too onerous (e.g. we do that for the increment interface for the timestepper), but that is going to be realistic in many cases (we are still only at v0.2 after all).

That said, I do agree to we need to ensure that all interested parties are aware and get a chance to have input on these changes. I've created an ["interface change"](https://github.com/CliMA/ClimateMachine.jl/labels/interface%20change) label which we can use for these sorts of changes in future, and added an item to the weekly meeting where we can discuss these.
