### ISSUE TITLE
Boyd-Vandeven filter

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimateMachine.jl#1391]
# Description

A bug is identified in the `χ(x)` formula at the filter [description](https://github.com/CliMA/ClimateMachine.jl/blob/765e41d598bc7647043b9424524c20ed78ddfbdd/src/Numerics/Mesh/Filters.jl#L175) and the [function](https://github.com/CliMA/ClimateMachine.jl/blob/765e41d598bc7647043b9424524c20ed78ddfbdd/src/Numerics/Mesh/Filters.jl#L215).

## Expected behavior
A simple fix is 
`sqrt(-log(1 - 4 * (abs(x) - 0.5)^2) / 4 / (abs(x) - 0.5)^2)`

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by slifer50** [comment]
@jiahe23 I've added your suggestion in PR #1392
