### ISSUE TITLE
Silent mode for running the model

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimateMachine.jl#1409]
# Description

It would be great to have an option to run the model without the print statements on the screen. Sometimes they are useful, but sometimes they just clutter the space in terminal. 

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [X] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jkozdon** [comment]
We use the logger, so you can get some decreased output by setting the environment variable `JULIA_LOG_LEVEL=WARN`

My guess is there are some `@info` logging that should be `@debug`

```sh
❯ rg --count @info
test/testhelpers.jl:1
src/Driver/Driver.jl:3
src/Driver/solver_configs.jl:2
src/Driver/driver_configs.jl:4
src/Diagnostics/groups.jl:3
test/Ocean/ShallowWater/GyreDriver.jl:5
tutorials/Numerics/DGMethods/nonnegative.jl:4
test/Ocean/SplitExplicit/hydrostatic_spindown.jl:3
test/Numerics/DGMethods/horizontal_integral_test.jl:1
test/Numerics/DGMethods/integral_test.jl:1
test/Numerics/DGMethods/integral_test_sphere.jl:2
test/Numerics/DGMethods/vars_test.jl:1
test/Numerics/SystemSolvers/poisson.jl:3
src/Driver/Callbacks/Callbacks.jl:3
src/Ocean/HydrostaticBoussinesq/Courant.jl:2
src/Utilities/Checkpoint/Checkpoint.jl:1
test/Ocean/ShallowWater/2D_hydrostatic_spindown.jl:3
test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl:5
test/Numerics/DGMethods/compressible_Navier_Stokes/ref_state.jl:2
test/Numerics/DGMethods/conservation/sphere.jl:3
test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl:6
test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl:6
test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl:6
test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl:6
test/Numerics/DGMethods/Euler/acousticwave_mrigark.jl:4
test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl:1
test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl:1
test/Atmos/Parameterizations/Microphysics/KM_ice.jl:1
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl:7
test/Numerics/DGMethods/advection_diffusion/periodic_3D_hyperdiffusion.jl:7
test/Numerics/DGMethods/Euler/isentropicvortex.jl:6
test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl:4
test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl:7
test/Numerics/DGMethods/advection_diffusion/pseudo1D_heat_eqn.jl:6
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion.jl:7
test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl:5
test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl:3
test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model_1dimex_bgmres.jl:7
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_mrigark_implicit.jl:7

❯ rg --count @debug
test/Ocean/ShallowWater/GyreDriver.jl:1
test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl:1
```

**Comment by kpamnany** [comment]
> We use the logger, so you can get some decreased output by setting the environment variable `JULIA_LOG_LEVEL=WARN`

Ahh, that's right! And alternatively with `ClimateMachine.init(log_level = "warn")` or by running the tutorial with `--log-level=warn`.

But all of the `@info`s etc. do need to be curated at some point as Jeremy points out.

**Comment by jkozdon** [comment]
Maybe this should be close and merged with #134?

**Comment by trontrytel** [comment]
> > We use the logger, so you can get some decreased output by setting the environment variable `JULIA_LOG_LEVEL=WARN`
> 
> Ahh, that's right! And alternatively with `ClimateMachine.init(log_level = "warn")` or by running the tutorial with `--log-level=warn`.
> 
> But all of the `@info`s etc. do need to be curated at some point as Jeremy points out.

So just to be sure I understand: If we were to switch from `@info` to `@warn` then doing `ClimateMachine.init(log_level = "warn")` would suppress the prints on screen?

**Comment by trontrytel** [comment]
Anyhow, I'll just leave a comment on https://github.com/CliMA/ClimateMachine.jl/issues/134 and close this one.

**Comment by trontrytel** [comment]
Closing because its part of https://github.com/CliMA/ClimateMachine.jl/issues/134

**Comment by kpamnany** [comment]
> So just to be sure I understand: If we were to switch from `@info` to `@warn` then doing `ClimateMachine.init(log_level = "warn")` would suppress the prints on screen?

No switching to `@warn`. As it is now, setting the log level to "warn" would silence the`@info`s.
