### ISSUE TITLE
Add i-th timestep to ODESolvers

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1419]
# Description

For diagnostic / debugging purposes, we should add the i-th timestep to the solver somewhere, similar to time and `dt`.

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by charleskawczynski** [comment]
We should also provide a way to run a simulation to a maximum number of timesteps.

**Comment by jkozdon** [comment]
> We should also provide a way to run a simulation to a maximum number of timesteps.

Good idea. This would be useful for debugging and profiling!

(I've almost added it a couple times, but just hacked the behavior when I needed it)

**Comment by kpamnany** [comment]
❔ Can't you use `solve!(..., numberofsteps = X)`?

**Comment by charleskawczynski** [comment]
> ❔ Can't you use `solve!(..., numberofsteps = X)`?

Ah, I think should work (I had originally looked for this in the `SolverConfiguration`), thanks!

**Comment by charleskawczynski** [comment]
Oops, we should still add a way to compute the i-th timestep, thanks @kpamnany 😄
