### ISSUE TITLE
Create data sets directory in tests, using Artifacts. Migrate to that.

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimateMachine.jl#1427]
https://github.com/CliMA/ClimateMachine.jl/blob/master/test/Common/Thermodynamics/data_tests.jl

**Comment by kmdeck** [comment]
fixed in this PR
https://github.com/CliMA/ClimateMachine.jl/pull/1425

**Comment by charleskawczynski** [comment]
@kmdeck should we close this?
