### ISSUE TITLE
collect all moisture sources, add them to density once

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimateMachine.jl#1466]
As suggested by @tapios below. @charleskawczynski, I don't think we have a mechanism for it right now?

My preference would be to collect all mass sources owing moisture sources and add them as a density source where we specify the equations of motion, not piece-by-piece where we define parameterizations.

_Originally posted by @tapios in https://github.com/CliMA/ClimateMachine.jl/pull/1440#discussion_r470810399_

**Comment by charleskawczynski** [comment]
> My preference would be to collect all mass sources owing moisture sources and add them as a density source where we specify the equations of motion, not piece-by-piece where we define parameterizations.

This is how the tendency specification layer works, which is now complete for the atmoshpere.
