### ISSUE TITLE
Heartbeat with synchronised error handling

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimateMachine.jl#1510]
# Description

We want to be able to dump the full state when an error occurs inside the DG kernels. The challenge is determining when this occurs and flagging this on all ranks. A simple idea is to do something like
```julia
try
   # do stuff
   err = MPI.Allreduce(false, max, comm)
catch e
   err = MPI.Allreduce(true, max, comm)
finally
   if err
      # write state to disk
      error("now quit")
   end
end
```

The problem with this approach is that if `# do stuff` involved communication, we might end up in a state where ranks without errors are stuck waiting on communication from the errored ranks.

Since our errors will mostly occur inside events, one idea is to build this into an event wrapper
```julia
struct HeartbeatEvent <: Event
   ev::Event
   callback
end
function wait(h::HeartbeatEvent)
   try
     wait(h.ev)
     err = MPI.Allreduce(false, max, comm)
   catch e
     err = MPI.Allreduce(true, max, comm)
   finally
     if err
      h.callback()
      error("now quit")
     end
   end
end
```
cc: @kpamnany @vchuravy 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
Alternatively, could we use the MPI error handling machinery?
https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node217.htm#Node217

**Comment by kpamnany** [comment]
Done in #2074.
