### ISSUE TITLE
references in docs

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimateMachine.jl#152]
Would be nice if there was a way keep citations in a global bibtex file and have them rendered nicely in the docstrings.

See https://github.com/JuliaDocs/Documenter.jl/issues/379, [this discussion](https://discourse.julialang.org/t/citations-in-docs/5066/36) and the unregistered [Citations.jl](https://github.com/adamslc/Citations.jl) package.

**Comment by charleskawczynski** [comment]
For local references, [this repo](https://jdeldre.github.io/ViscousFlow.jl/latest/#References-1) uses simple markdown, which looks nice!

**Comment by simonbyrne** [comment]
It does. I wonder if it works from in docstrings?
