### ISSUE TITLE
Change `q_vap_saturation_generic` kwargs to args

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1533]
# Description

Just to track this, we should change the `q_vap_saturation_generic` kwarg to a positional arg, since kwargs have performance issues on the gpu. See discussion [here](https://github.com/JuliaGPU/KernelAbstractions.jl/issues/114#issuecomment-664583781).

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by tapios** [comment]
You can just change it to having two separate functions: `q_vap_saturation_liquid` and `q_vap_saturation_ice`. It seems that would work easily in all places where the generic function is currently used.

**Comment by charleskawczynski** [comment]
Closed by #1539
