### ISSUE TITLE
Bomex update

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimateMachine.jl#1545]
@tapios , @akshaysridhar , @szy21 , @charleskawczynski 

I have run Bomex in Equilibrium and NonEquilibrium configurations. Both simulations crash after an hour with `ERROR: LoadError: abs(δρ) > 0.0001`. Not sure if this is to be expected for now? The default setup was to run it for 30 minutes.

Here are results from the first hour:
![Bomex_update 001](https://user-images.githubusercontent.com/1196696/92973464-1ae8d080-f439-11ea-9d9c-d4d6275a408f.jpeg)

At 69 minutes both runs have similar cloud top heights and `q_liq`. At the earlier times the `NonEquilibrium` model has larger vertical velocities because of larger latent heat release. This is caused by the initial condition differences between the two models, I think.

**Comment by charleskawczynski** [comment]
Is this the LES or single stack?

**Comment by trontrytel** [comment]
> Is this the LES or single stack?

LES

**Comment by szy21** [comment]
If you would like to run it longer, simply increase the numbers here (@akshaysridhar we should make this clear in the docs):
```
check_cons = (
        ClimateMachine.ConservationCheck("ρ", "3000steps", FT(0.0001)),
        ClimateMachine.ConservationCheck("ρe", "3000steps", FT(0.0025)),
    )
```
These are for 30 min simulations, so I would increase them by e.g. a factor of 12 if you run a 6h simulation.

**Comment by trontrytel** [comment]
> If you would like to run it longer, simply increase the numbers here (@akshaysridhar we should make this clear in the docs):
> 
> ```
> check_cons = (
>         ClimateMachine.ConservationCheck("ρ", "3000steps", FT(0.0001)),
>         ClimateMachine.ConservationCheck("ρe", "3000steps", FT(0.0025)),
>     )
> ```
> 
> These are for 30 min simulations, so I would increase them by e.g. a factor of 12 if you run a 6h simulation.

Thanks! I did not realise there was something else to do when extending the time. 

Would be good to make it automatic choice, based on simulation time?

**Comment by szy21** [comment]
> Would be good to make it automatic choice, based on simulation time?

Good point. @charleskawczynski @akshaysridhar any thoughts?

**Comment by akshaysridhar** [comment]
> > If you would like to run it longer, simply increase the numbers here (@akshaysridhar we should make this clear in the docs):
> > ```
> > check_cons = (
> >         ClimateMachine.ConservationCheck("ρ", "3000steps", FT(0.0001)),
> >         ClimateMachine.ConservationCheck("ρe", "3000steps", FT(0.0025)),
> >     )
> > ```
> > 
> > 
> > These are for 30 min simulations, so I would increase them by e.g. a factor of 12 if you run a 6h simulation.
> 
> Thanks! I did not realise there was something else to do when extending the time.
> 
> Would be good to make it automatic choice, based on simulation time?

Yeah I think now this should all be updated based on a full nightly test time, for the complete `timeend = 6 hour` simulation

**Comment by charleskawczynski** [comment]
I kind of like the conservative/concrete tolerances. Maybe we just a comment, for now, near `timeend` about the need to increase conservation tolerances due to the accumulation of errors over time?

**Comment by trontrytel** [comment]
Final update on this. Here is the time evolution for the two options for the whole 6 hours simulation time:

![bomex_fin 002](https://user-images.githubusercontent.com/1196696/92985802-ec83e900-f46a-11ea-996c-9c404c7ebaff.jpeg)

And here is the last hour average for the two options, compared to the plot from the paper:

![bomex_fin 001](https://user-images.githubusercontent.com/1196696/92985812-01f91300-f46b-11ea-9dbb-da2816c76b44.jpeg)

I think this looks good. Should come back to it as a nightly test, once we have nightly tests.
