### ISSUE TITLE
Add interpolation step to dict_of_nodal_states

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimateMachine.jl#1556]
# Description
@charleskawczynski and I would like to add the interpolation helper functions here:
https://github.com/CliMA/ClimateMachine.jl/blob/f5798ef909c03b15363f2ead410979ccc4c3e887/tutorials/Land/Soil/interpolation_helper.jl
into the `dict_of_nodal_states` action. 

# Additional context

Many users who plot output from the `SingleStackConfiguration` will want to smooth over the discontinuities at element boundaries. 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by charleskawczynski** [comment]
Maybe better to put it in [`get_vars_from_nodal_stack`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Utilities/SingleStackUtils/SingleStackUtils.jl#L42) and [`get_vars_from_element_stack`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Utilities/SingleStackUtils/SingleStackUtils.jl#L97), `dict_of_nodal_states` just collects them from `get_vars_from_nodal_stack`.
