### ISSUE TITLE
Printing resource used information

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimateMachine.jl#1628]
Hello all! 

# Description

I have just recently tried to run an example to get familiar with the ClimateMachine codebase. For instance, I have tested just the [rising bubble](https://github.com/CliMA/ClimateMachine.jl/blob/master/tutorials/Atmos/risingbubble.jl) and looked at the output. As I'm reading the output and learning how to interpret it, I asked myself if the GPU resource was actually utilized.

# Additional context

In other projects I am familiar with, for instance in PETSc this info is printed when using `-log_view` or in [libCEED](https://github.com/CEED/libCEED) we decided to print out the resource info in every example, as this can be requested at runtime, and users might believe they have specified to run with the available GPU or CPU backend but then didn't realize that the resource actually used might not have been the intended one because they might have had a typo in their CL arguments and the fallback mechanism defaulted it.

Example of a libCEED example output where the Ceed specification (or resource) is printed out:

<details><summary>Click here to expand</summary>
<p>

```
$ ./ex1-volume
Selected options: [command line option] : <current value>
  Ceed specification [-c] : /cpu/self
  Mesh dimension     [-d] : 3
  Mesh order         [-m] : 4
  Solution order     [-o] : 4
  Num. 1D quadr. pts [-q] : 6
  Approx. # unknowns [-s] : 262144
  QFunction source   [-g] : header

Mesh size: nx = 16, ny = 16, nz = 16
Number of mesh nodes     : 274625
Number of solution nodes : 274625
Computing the quadrature data for the mass operator ... done.
Computing the mesh volume using the formula: vol = 1^T.M.1 ... done.
Exact mesh volume    :  2.3561944901923
Computed mesh volume :  2.3561944901921
Volume error         : -2.7444713168734e-13
```

</p>
</details>

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jkozdon** [comment]
This is a good suggestion! Thanks.

Looking at [`driver_configs.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/f3c3225acf7504b6fc58dc1a1a8232eb6004f00b/src/Driver/driver_configs.jl) and  [`solver_configs.jl`](https://github.com/CliMA/ClimateMachine.jl/blob/f3c3225acf7504b6fc58dc1a1a8232eb6004f00b/src/Driver/solver_configs.jl) it seems like each configuration is printing custom info. Atmos prints different stuff than ocean, etc..

It seems that there should be output somewhere which dumps all the generic info for the run (such as array type) regardless of the configuration.

**Comment by jakebolewski** [comment]
IMO the least surprising option would be just to be explicit about the backend (cpu / gpu / etc.) and fail otherwise if the backend resources cannot be initialized.

**Comment by valeriabarra** [comment]
I think what @thomasgibson  did in this [test](https://github.com/CliMA/ClimateMachine.jl/blob/544b6eca3b40a1e3ea7d08e408dade0a32afb4b0/test/Numerics/DGMethods/advection_diffusion/direction_splitting_advection_diffusion.jl#L191) (and now is merged on master) is another easy way to show not the resource, but the array type, like it is done in PETSc for instance. This way it is an effective way of communicating if you are really running on the GPU or not.
