### ISSUE TITLE
Dycoms in master breaks at 1.7 simulated hours

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimateMachine.jl#1663]
### Description

The dycoms simulation in master breaks at ~1.7 simulated hours with the error message "maxiter reached in saturation_adjustment". I don't think we need to try to fix this now, just to let people know about the issue.

**Comment by szy21** [comment]
@akshaysridhar based on our conversation this afternoon we can close it?

**Comment by charleskawczynski** [comment]
bump
