### ISSUE TITLE
[Ocean] Kwarg in ocean driver configurations for passing pre-constructed grids

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimateMachine.jl#1680]
In both the `OceanSplitExplicitConfiguration` and the `OceanBoxGCMConfiguration`, parameters of the grid must be specified in the object `model.problem` (where `model` is `HydrostaticBoussinesqModel` or `OceanModel`.

For example the grid construction is done here for `OceanBoxGCMConfiguration`:

https://github.com/CliMA/ClimateMachine.jl/blob/544bfaac0872092cb59cb6163cb5628fed2e6d2d/src/Driver/driver_configs.jl#L309-L327

and here for `OceanModel`:

https://github.com/CliMA/ClimateMachine.jl/blob/544bfaac0872092cb59cb6163cb5628fed2e6d2d/src/Driver/driver_configs.jl#L364-L395

However, I think it would be useful (and would simplify writing new `problem` types) to be able to pass a `DiscontinuousSpectralElementGrid` directly to these `Configuration` functions. That will allow us to separate the specification of initial conditions via `model.problem` from the specification of the grid geometry and thereby reduce some of the boiler plate involved in setting up new problems. It will also allow us to reuse simple `problem` definitions (for example, consisting merely of a list of functions for each state field) for Cartesian and spherical geometries.

cc @blallen

**Comment by glwagner** [comment]
I think that as a short term solution to this issue, we simply add a kwarg `grid = nothing` to these functions which preserves existing functionality when the kwarg `grid` is not provided. In the long term, once we have decent abstractions for building grids (and thus feel comfortable changing our tests), we may be able to remove grid construction entirely from this function.

**Comment by kpamnany** [comment]
You can certainly add additional constructors or a new keyword argument, but apart from building the grid, these constructors don't do much/anything. I would think that moving grid construction to the experiment code would _increase_ rather than reduce boilerplate.

Also, I'm not getting the connection between this code and `model.problem`? `AtmosProblem` is used by (I think?) all atmosphere experiments.

**Comment by glwagner** [comment]
@kpamnany right, this is an easy change for us, just want to raise the issue first so we (meaning the ocean peeps) are all on the same page before I submit a PR.

The notion of a "problem" struct for us currently entangles grid information, boundary conditions, and initial conditions. However, constructing new scientific experiments requires defining new structs. This creates boilerplate when writing new experiments. We can fix the problem by generalizing the `problem` type --- but here I'm looking for a short term fix while we consider more extensive changes to the API that would negate a generalization of `problem`.

**Comment by glwagner** [comment]
> but apart from building the grid, these constructors don't do much/anything.

Yes, I agree, that is part of the issue here. I think we can improve the setup workflow by providing functions and objects whose job is more specific, eg, a function that sets up simple Cartesian grids that can be used along with a `BalanceLaw` to build a solver.

**Comment by glwagner** [comment]
This was more or less resolved by #1716
