### ISSUE TITLE
Formatter violates order-of-operations rules for julia syntax

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimateMachine.jl#1721]
I recently discovered this diff after applying `.dev/climaformat.jl` to my code:

![image](https://user-images.githubusercontent.com/15271942/98448575-ede43180-20fa-11eb-82e9-2ded8642022f.png)

Notice the change from

```julia
Ψ(x, L) = exp(-x^2 / 2L^2) # a Gaussian
```

to

```julia
Ψ(x, L) = exp(-x^2 / 2 * L^2) # a Gaussian
```

But these are not equivalent, since

```julia
julia> L = 2
2

julia> 1 / 2L^2
0.125

julia> 1 / 2 * L^2
2.0
```

Should we change the formatter so that it only changes the way code _looks_ (not functions)? This is a potential source of subtle and devious bugs in scientific code.

I personally find the ability to write constructs like `2a` to be a beautifully literate aspect of julia syntax and it would be a shame to throw it away.

**Comment by jkozdon** [comment]
Seems like a bug in JuliaFormatter. Probably should be reported.

**Comment by simonbyrne** [comment]
It seems to be fixed in the current version of JuliaFormatter. We just need to upgrade.

**Comment by glwagner** [comment]
Ah thanks for the quick responses. #1722 should do it I think.
