### ISSUE TITLE
Attaching a debugger

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimateMachine.jl#1777]
### Description

Just porting here my attempts at attaching a debugger in Julia, from our Slack conversation, so that it is easily retrievable.

Out of curiosity and personal interest, I wanted to figure out a good way to attach a debugger in Julia.
In testing different possible ways to debug our code, I tried the following options:

1. `Debugger.jl`
2. `Run and Debug`  [function in VSCode](https://www.julia-vscode.org/docs/stable/userguide/debugging/)
3. `@enter`  and `@run`  [macros from the Julia REPL in VSCode](https://www.julia-vscode.org/docs/stable/userguide/debugging/#Debugging-code-from-the-REPL-1)

All of these, I tried  both when using the GPU and for CPU runs only. And the one from the REPL (i.e., option 3 was a serial run).
I tried testing these debugging options with a simple tutorial, on master , with git diff  clean (so I know that normally this tutorial runs just fine). I used the tutorials/Atmos/dry_rayleigh_benard.jl just for simplicity.
In all of the cases above, the program throws an InterruptException when executing [this line](https://github.com/CliMA/ClimateMachine.jl/blob/66eaa2e9e53ecfeaa92d2e60e0ae5e2810e1a154/tutorials/Atmos/dry_rayleigh_benard.jl#L219). Then the program either crashes with a Segmentation fault (when using Debugger.jl ) or exits with the following message

```
DryRayleighBenardTest: Error During Test at /home/valeria/CliMA/ClimateMachine.jl/tutorials/Atmos/dry_rayleigh_benard.jl:215
  Got exception outside of a @test
Test Summary:         | Error  Total
DryRayleighBenardTest |     1      1
```

when using option 2 and 3.

If anyone has experience with any debugger in Julia and has any clue on what is going on, I'd greatly appreciate it.

I think a lot of CliMA folks could benefit from the solution

**Comment by simonbyrne** [comment]
[JuliaInterpreter.jl](https://github.com/JuliaDebug/JuliaInterpreter.jl) is another (I believe this is what VSCode uses in the backend).

**Comment by simonbyrne** [comment]
The problem with Debugger.jl appears to be due to https://github.com/JuliaDebug/Debugger.jl/issues/276

**Comment by simonbyrne** [comment]
It looks the problem in all cases is this one: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/440

**Comment by valeriabarra** [comment]
Ooooh, thanks for looking into this and finding that PR! I will try again once they fixed it! :crossed_fingers:

**Comment by valeriabarra** [comment]
This [PR #442](https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/442) fixed the issue, at least with Debugger.jl! 

Now I hope it can be also fixed in the VSCode extension so that we could have a nice GUI for debugging

**Comment by simonbyrne** [comment]
Looks like they need to upgrade their dependencies: https://github.com/julia-vscode/julia-vscode/issues/1793

**Comment by valeriabarra** [comment]
Thanks Simon for opening the issue with them!

**Comment by valeriabarra** [comment]
After the bux fixes in both Debugger.jl and now in the JuliaInterpreter for VSCode, I can close this issue and we are able to attach a debugger (at least for CPU runs) in CLiMA!
