### ISSUE TITLE
Explore a different type of cubed-sphere

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimateMachine.jl#1778]
### Description

This is probably not an urgent matter, considering the more pressing issues on the Numerics side we are all working on right now (e.g., split discretizations), but I'd like to write this down here more as food for thoughts for the people who are not familiar with this topic and would like to learn more.

There are several ways in which one can define a cubed-sphere. 

Among the most popular ones for the solution of PDEs are the equi-distant and the equi-anglular ones (but there is also one that is said to [best preserve Jacobians](https://journals.ametsoc.org/mwr/article/145/3/1083/103369/A-Nonhydrostatic-Multiscale-Model-on-the-Uniform)). See this nice interactive [tool](http://acmg.seas.harvard.edu/geos/cubed_sphere/CubeSphere_comparision.html) to observe the differences between them. 

Mainly, the equi-angular one is the most commonly found in the literature, because most papers that treat solutions of PDEs on cubed-spheres, for instance for the shallow-water equations, utilize Finite Differences approximations, for which the important aspect is that edges of elements that belong to different patches (or panels) of the cube are straight. But for Finite Element discretizations (either CG or DG), this requirement is not important, since elements are disjoint and there is no preference or requirement to have co-planar elements. Moreover, this type of cubed-sphere generates smaller elements around the corners of the cube, which might exacerbate the CFL condition more than you might expect, because smaller elements means closer nearest-neighboring nodes.  

On the other hand, the equi-distant cubed-sphere allows for a better ratio of smallest element to largest element, thus allows further apart nearest-neighboring nodes, and might help a little with CFL (see [this reference](https://rmets.onlinelibrary.wiley.com/doi/abs/10.1002/qj.49712253209)). 

Currently in the ClimateMachine, we have the [equi-angular](https://github.com/CliMA/ClimateMachine.jl/blob/3154952d43bf7048f3c633bcff8cd03f304fa6f6/src/Numerics/Mesh/Topologies.jl#L916-L971) one.

**Comment by tapios** [comment]
Thank you, @valeriabarra. I think this is important and relates to discussions @rafferrari, @sandreza and others have had about approximations to metric terms. It would be great if all you can connect on this.

**Comment by simonbyrne** [comment]
While not a cubed-sphere, another option for covering a sphere in quadrilaterals is [healpix](https://healpix.jpl.nasa.gov/), which has some nice properties for computing spherical harmonics.

**Comment by rafferrari** [comment]
I talked to Andre and he is planning to call a meeting with Daniel, Valeria and whoever else is interested to discuss options and plans for the metric terms.

**Comment by OsKnoth** [comment]
I think the standard is equal area. If any of our grids is finally described by high oder polynomials, the grid by itself has nothing to do wit computing the metric terms.
