### ISSUE TITLE
Add more tests to MoistThermodynamics

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#178]
There are several tests in MoistThermodynamics, but the interface functions are currently only tested for type-stability. It would be nice if we add more tests to the interface.

Also, perhaps we can reproduce some plots of phase diagrams in the docs.

**Comment by simonbyrne** [comment]
Are there published values or plots we can test against?

**Comment by charleskawczynski** [comment]
I'm sure there's something, I'll take a look

**Comment by trontrytel** [comment]
The single_eddy test I'm working on is a good test for many of the MoistThermodynamics components (saturation_adjustment, PhasePartition, etc) Should be fast enough to run as test

**Comment by charleskawczynski** [comment]
Some tests were added in #355 to test the case for `PhaseEquil(q_tot -> 0)` against `PhaseDry`.

**Comment by charleskawczynski** [comment]
Some interface consistency tests were added in #506.

**Comment by charleskawczynski** [comment]
I think Thermodynamics is pretty heavily tested now, so I think we can close or we should better refine this issue. Regarding the plots, @trontrytel are there plots we can compare [these profiles](https://clima.github.io/ClimateMachine.jl/latest/HowToGuides/Common/Thermodynamics/#Moist-Phase-in-thermodynamic-equilibrium) with?

**Comment by trontrytel** [comment]
I agree about closing this issue. 

Nothing comes to my mind about the plots. Do you want to check if they are consistent with some assumptions? Or just have another profile to show that the ones you test for are representative?

**Comment by charleskawczynski** [comment]
We have some test all of the thermo functions with these profiles, so I suppose they're tested for consistency in that way. I think having the doc plots is useful enough just for monitoring. I'll close for now.
