### ISSUE TITLE
Add assertion that dycoms with precip produces non-zero precip

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimateMachine.jl#1804]
### Description

Add assertion that the precip amount is non-zero for the test `gpu_dycoms_with_precip`.  Currently it just sanity checks that the test runs without crashing / non-zero exit.

cc @trontrytel

**Comment by trontrytel** [comment]
Here is a PR for it: https://github.com/CliMA/ClimateMachine.jl/pull/1813
