### ISSUE TITLE
EDMF kernels and methods are not robust to zero updraft area fraction

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/ClimateMachine.jl#1897]
### Description

The limit of `a_up=0` is physically acceptable, and the EDMF model implementation should be able to capture this problem. 

Many places in the code are not robust to this limit. Examples of this are `source!` and `flux` in `edmf_kernels.jl`, and other functions in `subdomain_thermo_states.jl`.

**Comment by yairchn** [comment]
@ilopezgp  why is a=0 an acceptable limit? 
what is θ_liq when a_up=0 (i.e. ρaθ_liq=0)?

**Comment by ilopezgp** [comment]
a=0 is acceptable because convection not always exists and therefore there aren't always updrafts. θ_liq_up does not exist if a=0, but if given any value it should be the grid-mean θ_liq.

**Comment by ilopezgp** [comment]
The entrainment and detrainment functions, as well as others, are ill-defined in the limit of a->0. Instead of fixing a minimum area fraction at each height and correcting the final area fraction to this minimum, we should have a minimum threshold below which source/sink terms for any updraft quantity are **not** computed nor used. 

That is, if the area fraction `a_up < a_up_min`, then we only use the left-hand side of the prognostic equation (advection equation), without any right-hand side terms. 

I am worried that some of the problems we are experiencing now are due to the ability of the model to create updrafts at any height from entrainment processes. This is **not** a correctly defined problem and should be avoided. The problems coming from this process are particularly critical due to the updraft variables being the prognostic ones, so we are computing the environmental values from very ill-defined quantities in the updrafts in the stable limit.

**Comment by ilopezgp** [comment]
PR #1903 assesses this problem for atomic evaluations. Successfully running a simulation with zero area fraction is yet to be done.

**Comment by ilopezgp** [comment]
PR #2143 fixes some additional issues related to zero area fraction.
