### ISSUE TITLE
Possible kernel race condition bug in mesh interpolation 

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimateMachine.jl#1919]
### Description 

Rare test error in GPU backend  in `test/Numerics/Mesh/interpolation.jl` that cannot be reproduced manually.

Ex:
https://buildkite.com/clima/climatemachine-ci/builds/1035#ece3c0dd-3bff-4690-a96b-eaa0c7a1fcd7/278-281

**Comment by kpamnany** [comment]
This was fixed by #1920 but wasn't closed when it merged.
