### ISSUE TITLE
Some additional git references for our contributors

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimateMachine.jl#1972]
### Description

Recently, I've shared some references that I found useful in the past with some prospective students/potential new contributors (e.g, an interactive [tool]( https://learngitbranching.js.org/) and [cheatsheet] (http://ndpsoftware.com/git-cheatsheet.html)). 

I'm wondering if we want to revamp our [Using `git`](https://clima.github.io/ClimateMachine.jl/latest/Contributing/#Using-git) doc page, including some of those. 
Additionally, lately the PETSc devs have revamped their docs (hooray) and have included an extensive section on [contributing with `git`](https://docs.petsc.org/en/latest/developers/integration/#git-instructions). I think we can take great inspiration from the info they included. 

What do you all think?

**Comment by bischtob** [comment]
I like it

**Comment by kpamnany** [comment]
There are many, many, many `git` tutorials, "cheatsheets", etc.; I think everyone has their own favorite. We intentionally decided to keep ours minimal and refer people to a couple of good ones. Personally, I feel it is redundant to write yet another, but if you'd like to add a separate page describing the workflow for opening a PR or something like that and link to it from our "Contributing" page, that's fine by me.

**Comment by valeriabarra** [comment]
@kpamnany  What do you think of the workflow examples/instructions given by the petsc folks? E could greatly take inpiration (cough cough copy them)

**Comment by kpamnany** [comment]
> @kpamnany What do you think of the workflow examples/instructions given by the petsc folks? E could greatly take inpiration (cough cough copy them)

It's a decent summary, but doesn't cover squashing or rebasing, both of which we'd like contributors to use. In general, I think it is better to add a link than copy something. [This](https://github.com/libuv/libuv/blob/master/CONTRIBUTING.md) is one of my favorites because it covers how to contribute from a cloned repo and touches on rebasing, but as I said, everyone has a favorite. 🤷‍♂️

**Comment by valeriabarra** [comment]
Absolutely, I agree that it is always better linking than copying. In this particular case, I was having in mind the readers to be mostly young prospective students (like the example I mentioned in this post), who might feel even more lost if, for a set of git instructions, they are re-directed to another scientific computing project. It is very easy when you are just getting started and inexperience to be able to extrapolate the necessary relevant content from other projects, and it is also confusing sometimes and can lead to "content fatigue" or "package fatigue" when referring to other scientific computing projects/packages.
