### ISSUE TITLE
Linear model seems to be called, at some point, with uninitialized data.

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1987]
### Description

I saw something a bit strange over the weekend.

It seems that, when using IMEX solver type, `flux_first_order!` seems to be called with uninitialized data:

```julia
-----------------------------------
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod, e_int=NaN, ρ=0.0, q_tot=NaN, T=NaN, maxiter=5, tol=71.75060234725578
state.ρ = 0.0
state.ρu = [0.0, 0.0, 0.0]
state.energy.ρe = 0.0
gravitational_potential(lm.atmos.orientation, aux) = 588.5999999999999
internal_energy(lm.atmos, state, aux) = NaN
```

I believe this was with this [driver](https://github.com/CliMA/ClimateMachine.jl/blob/master/experiments/AtmosLES/bomex_single_stack.jl), which should be reproducible by uncommenting [this line](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/linear.jl#L230). That should lead to failed saturation adjustment (since density is zero). Leaving the line commented (as is done in master) means that the function is still called with zero density-- but I believe the results appear okay.

I'd like to look into this more, but I'm still getting familiar with the linear and remainder models.

**Comment by mwarusz** [comment]
This is not a bug. It happens because we assemble the linear model matrix `A` by computing the linear tendency on a nonphysical state vector:
```
column A_i = A * [0, 0, ..., 1, 0, ..., 0]'
                             ^
                             i
```

**Comment by charleskawczynski** [comment]
Thanks @mwarusz, that makes sense. I just wanted to open an issue to track and make sure I followed up on this.
