### ISSUE TITLE
Filter `Nc` versus driver `Ncutoff`

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#2047]
Currently the driver `Ncutoff` means "[Keep all polynomial modes below `Ncutoff`](https://github.com/CliMA/ClimateMachine.jl/blob/711360d0386d2edbb0dc78d110c0c9a654f9e818/src/Driver/driver_configs.jl#L406-L414)" whereas the filter `Nc` means "[filter all modes `Nc` and higher".](https://github.com/CliMA/ClimateMachine.jl/blob/711360d0386d2edbb0dc78d110c0c9a654f9e818/src/Numerics/Mesh/Filters.jl#L101-L112)

I understand why this was done in #1953.

I fear this will lead to some confusion, so I wonder if we should change the meaning of `Nc` in the filter code or determine a better way to specify no filter in the driver.

cc: @valeriabarra @simonbyrne

**Comment by valeriabarra** [comment]
Thanks for opening the issue! I was indeed confused, because my understanding of its meaning was the one that we recently added to the driver, but then, when I heard you explaining that in the last sprint meeting it got me puzzled, because it sounded the opposite way. 

Yes, we should make sure this is unified, consistent and clear for the users

**Comment by valeriabarra** [comment]
Perhaps I am getting my self overly confused. 
[Here](https://github.com/Clima/ClimateMachine.jl/blob/711360d0386d2edbb0dc78d110c0c9a654f9e818/src/Numerics/Mesh/Filters.jl#L237-L242) it says "that zeros out polynomial modes greater than or equal to `Nc`", so this would be the same as it is in the driver, no? I.e., if we zero out those greater than `Nc`, it means we are effectively keeping the `cutoff order` nodes (with 0 < `cutoff order` < `N`)

**Comment by jkozdon** [comment]
To set, for examjple, `Ncutoff = 3` in the driver is the same as saying `Nc = 4` if directly using the cutoff filter.

So in the driver the mode `Ncutoff` is kept, but in the filter the mode `Nc` is zeroed out.

If we don't think this is a problem we can close the issue, I was just worried that this might lead to confusion in the future.

**Comment by valeriabarra** [comment]
I agree that it might be a bit confusing actually. 

Would you recommend changing the help docstring for the `cutoff-degree` option to something like

```
"--cutoff-degree"
        help = "tuple of horizontal and vertical polynomial degrees to keep when applying a cutoff filter (no space before/after comma)"
```
?
