### ISSUE TITLE
Bug in Interpolation module

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimateMachine.jl#2048]
### Description

The [`config_diagnostics`](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/test/Atmos/EDMF/stable_bl_edmf.jl#L233-L266) is added to the stable boundary layer edmf driver. It is a direct copy from the [bomex edmf driver](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/test/Atmos/EDMF/bomex_edmf.jl#L250). The bomex driver works out fine and create netcdf files as expected. the stable boundary layer driver gives the following warning 
```
┌ Warning: Diagnostics AtmosLESCore: can only be used with the `EquilMoist` moisture model
└ @ ClimateMachine.Diagnostics ~/CliMA/ClimateMachine.jl/src/Diagnostics/atmos_les_core.jl:170
┌ Warning: Diagnostics AtmosLESCore: can only be used with the `EquilMoist` moisture model
└ @ ClimateMachine.Diagnostics ~/CliMA/ClimateMachine.jl/src/Diagnostics/atmos_les_core.jl:221
```
Instead of `SBL_EDMF_DumpState.nc`, it creates a `SBL_EDMF_AtmosLESDefault.nc`.
stable boundary layer case is a dry case that doesn't have the `EquilMoist` model.

**Comment by kpamnany** [comment]
On `master`, this experiment is calling the [`config_diagnostics`](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/experiments/AtmosLES/stable_bl_model.jl#L332) from `stable_bl_model.jl` which is included into this experiment [`here`](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/test/Atmos/EDMF/stable_bl_edmf.jl#L13). Your new  [`config_diagnostics`](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/test/Atmos/EDMF/stable_bl_edmf.jl#L233) takes 2 parameters; but the [`call`](https://github.com/CliMA/ClimateMachine.jl/blob/3e81b1742433b1df148be52483c14c95f1b37e12/test/Atmos/EDMF/stable_bl_edmf.jl#L175) is passing just 1.

If you fix the call, it should work, but I suggest also renaming the function, maybe to `config_ss_debug_diagnostics` or something like that.

**Comment by kpamnany** [comment]
As an update here, the corrected version threw a different error:
```
ERROR: LoadError: BoundsError: attempt to access 0-element Array{Float64,1} at index [1]
Stacktrace:
 [1] getindex at .\array.jl:809 [inlined]
 [2] ClimateMachine.Mesh.Interpolation.InterpolationBrick(::DiscontinuousSpectralElementGrid{Float64,3,(1, 1, 1),8,CUDA.CuArray,Tuple{CUDA.CuArray{Float64,1},CUDA.CuArray{Float64,1},CUDA.CuArray{Float64,1}},Tuple{CUDA.CuArray{Float64,2},CUDA.CuArray{Float64,2},CUDA.CuArray{Float64,2}},CUDA.CuArray{Float64,3},CUDA.CuArray{Float64,4},CUDA.CuArray{Int64,1},CUDA.CuArray{Int64,2},CUDA.CuArray{Int64,3},ClimateMachine.Mesh.Topologies.StackedBrickTopology{3,Float64,2},Tuple{Array{Float64,2},Array{Float64,2},Array{Float64,2}},ClimateMachine.Mesh.Grids.MinNodalDistance{Float64}}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Cygwin64\home\kpamn\ClimateMachine.jl\src\Numerics\Mesh\Interpolation.jl:246
```
This is a bug in the Interpolation code, fix from @skandalaCLIMA incoming.
