### ISSUE TITLE
Missing documentation and errors in SurfaceFluxes.get_flux_coefficients

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/ClimateMachine.jl#2068]
### Description

The source of the function `get_flux_coefficients` is not documented in the code base, and I could not find it in the Nishizawa and Kitamura paper. Either the rationale or the source for this function should be documented in the code.

I have found that this function is ill-posed under unstable stratification, since it contains logarithms of the form

`log(z / z0 - psi_m),`
`log(z / z0 - psi_h),`

and the function inside the logarithm may be negative under unstable stratification. I cannot solve this issue because I don't know where the formulation comes from.

**Comment by charleskawczynski** [comment]
It looks like we added `get_flux_coefficients` in #1622, which was mainly focused on refactoring the universal function. IIRC, putting that PR together started a bit chaotic. It's very possible that `get_flux_coefficients` may have been a bad copying casualty. From what I can tell, it looks like we should just remove `get_flux_coefficients` and return the result of `exchange_coefficients`. @ilopezgp, can you confirm?

**Comment by ilopezgp** [comment]
@charleskawczynski thanks for digging into this issue. I would like @akshaysridhar's opinion before removing this function, just in case.

About `exchange_coefficients`, my understanding is that this function right now returns the values of (20) and (21) from Nishizawa and Kitamura, which are equations used only for verification purposes (they return the diffusivity given a flux). 

Nevertheless, I think you are right that we can use a slight modification of this function. However, if we want to use the `K`s in the boundary conditions, I believe we cannot use them to substitute the `C` in the Bulk formulas. The reason is that `K` times a gradient equals the flux (what we want), but the Bulk BC seem to use a difference instead of a gradient. Thoughts on this? 

@szy21 might provide valuable insight in this discussion.

**Comment by szy21** [comment]
Yes, we cannot use the `K` to substitute `C` in the bulk formulas. The formulation of C_exchange seems to be the same as the one used in pycles (except that the drag coefficient for heat is not divided by Pr in clima?). But I don't know which reference is used in pycles.

**Comment by ilopezgp** [comment]
Thanks @szy21, this was extremely helpful!! 

I verified that these expressions are taken from Byun (1990). I also checked and in fact the erroneous behavior comes from a typo in #1622 (the `-psi` should be outside the logarithm). I will open a PR and fix this issue.
