### ISSUE TITLE
Test MoistThermo's `relative_humidity` for correctness

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#570]
The MoistThermo relative humidity equation needs to be fixed, and tested

**Comment by tapios** [comment]
Test that you get `rh=1` when `q_tot >= q_vap_sat` for a range of conditions.

**Comment by charleskawczynski** [comment]
The relative humidity equation was fixed in #581, but adding the following test fails. For reference, the first three input values of the failing cases are printed here:
```julia
  rtol = sqrt(eps(FT))
  e_int, ρ, q_tot, q_pt, T, p, θ_liq_ice = MT.tested_convergence_range(FT, 50)
  RH = relative_humidity.(T, p, e_int, q_pt)
  q_vap_sat = q_vap_saturation.(T, ρ, q_pt)
  saturated = q_tot .>= q_vap_sat
  rh_unity = isapprox.(RH, FT(1), rtol=rtol)
  rh_test = map((x,y)-> x && y, rh_unity, saturated)
  i_inputs = findall(rh_test)[1:3]
  @test all(rh_test)
  @show e_int[i_inputs] # = [-84294.67404055291, -87869.75090612845, -88368.04027152681]
  @show ρ[i_inputs]     # = [0.13309288249358406, 0.12269764622479777, 0.10974046287375958]
  @show q_tot[i_inputs] # = [2.4757281002123955e-9, 7.428177674853137e-10, 6.902628628146144e-10]
  @show T[i_inputs]     # = [155.67711210172115, 150.69447395048323, 150.0]
  @show p[i_inputs]     # = [5946.550895099254, 5306.6335808151125, 4724.366587835346]
```
Since `relative_humidity` is in master, this can currently be tested in the REPL.

**Comment by tapios** [comment]
Isn't the issue just that `relative_humidity` is not capped at `1` in the code? That is, when conditions are saturated, `relative_humidity` can exceed `1`, but the test tests for approximate equality to `1`? We should just cap RH at `1` in the source code regardless.

**Comment by charleskawczynski** [comment]
> Isn't the issue just that relative_humidity is not capped at 1 in the code?

Correct, we [don't cap RH](https://github.com/climate-machine/CLIMA/blob/master/src/Common/MoistThermodynamics/MoistThermodynamics.jl#L1087-L1094). However, I just looked at the spread of RH returned from `tested_convergence_range`, and none are above 1. Probably because [we cap the tested range of `q_tot`](https://github.com/climate-machine/CLIMA/blob/master/src/Common/MoistThermodynamics/states.jl#L292). Perhaps this is why it's failing though, this means that `q_sat` and `relative_sat` no longer uniquely map to `q_tot` (due to the `max` call).

**Comment by charleskawczynski** [comment]
@tapios does #1289 close this?

**Comment by tapios** [comment]
Yes.
