### ISSUE TITLE
Need saturation vapor pressure over possible mixture of liquid and ice

### ISSUE THREAD

**Issue by tapios** [CliMA/ClimateMachine.jl#641]
We need to add a default option to get the saturation vapor pressure over a possible mixture of liquid and ice, as given by the phase partitioning object. For a liquid fraction `liq_frac`, this means calling

`saturation_vapor_pressure(air_temperature(ts), liq_frac * FT(LH_v0) + (1-liq_frac) * FT(LH_s0), FT(cp_v) - liq_frac * FT(cp_l) - (1-liq_frac) * FT(cp_i))`

This should be the default saturation vapor pressure when no explicit `Liquid` or `Ice` argument is given.

It should also be the saturation vapor pressure in the calculation of relative humidity.

**Comment by charleskawczynski** [comment]
Closed by #1050
