### ISSUE TITLE
CLIMA vs CLIMA.jl - name conflict with attobot (for registering)

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#84]
We will want to register `CLIMA` eventually and, according to [attobot](https://github.com/attobot/attobot#Usage) "It will only operate on packages with the standard ".jl" suffix (all other packages will be ignored)." So, it seems that currently, only `CLIMA.jl` is register-able.

This is not urgent, but I just wanted to start a conversation about it.

**Comment by glwagner** [comment]
I think `CLIMA.jl` is a great package name.

**Comment by simonbyrne** [comment]
I think that restriction will go away when attobot is retired in the near future (in favour of [Registrator.jl](https://github.com/JuliaComputing/Registrator.jl)). That said, the .jl suffix is nice as it makes searching very easy.
