### ISSUE TITLE
Clarify README in MPI section

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#890]
# Description

Every new user seems to run into MPI configuration problems and I think that the MPI debugging section could be more clear. Specifically, the section

> If you are having problems building MPI.jl then most likely you need to set the environment variable JULIA_MPI_PATH.

It would be nice if we say what the environment variable should be set to (and perhaps give examples). It would be nice to clarify if the path should be set to the MPI installation directory, or the MPI/bin/ directory, or that it doesn't matter which (if it in fact doesn't matter). I think we can really expand on this section in terms of how to get MPI configured, or point to where there is more information or detailed instructions on how to get MPI configured.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
We can probably just remove that section, and refer users to the MPI.jl installation docs.

**Comment by claresinger** [comment]
The wiki page currently has some useful info regarding MPI. Maybe this can get incorporated into the README? https://github.com/climate-machine/CLIMA/wiki/Common-execution-errors

One other note: @szy21 and I both had to manually `build MPI` from the REPL to get MPI and CLIMA working. Why doesn't this happen automatically?

**Comment by simonbyrne** [comment]
> One other note: @szy21 and I both had to manually `build MPI` from the REPL to get MPI and CLIMA working. Why doesn't this happen automatically?

It did: the problems were usually when switching to use different MPI implementations. This should no longer be an issue as of #933.

**Comment by charleskawczynski** [comment]
Closing now that ClimateMachine ships with MPI!
