### ISSUE TITLE
Revamp Reference State Temperature Profiles

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimateMachine.jl#939]
# Description

We need to revamp the reference state module to match the design docs. This involves removing the linear temperature profile, making the adiabatic temperature profile independent of the linear profile, and for moist reference states, solving a nonlinear problem to calculate the reference state relative humidities when using a decaying virtual temperature profile. We also need to include tests to test that physical balances and relationships hold (e.g., hydrostatic balance).

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by tapios** [comment]
This is essentially the same as #882.
