### ISSUE TITLE
Additional LES diagnostics

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimateMachine.jl#943]
# Description

Some more diagnostics in the LES would be helpful. Here is the diagnostics we currently have in the LES: https://gist.github.com/akshaysridhar/cc7888d27a93237eee4f8373630a0d6a. Some useful diagnostics include (I checked the ones we already have in current master):

### default

Profiles (t,z):

- [x] u, v ,w, q_tot, thl, e_int
- [x] ρ 
- [x] u'u', v'v', w'w'
- [x] q_tot'q_tot', e_int'e_int', thl'thl'
- [x] w’ρ’, w’u', w’v', w’q_tot', w’thl'
- [x] w'e_int', q_tot'thl', q_tot'e_int' 
- [x] cloud fraction: horizontal area (fraction) where q_liq>0

Timeseries (t):

- [ ] liquid water path: lwp (vertical integral of ρ q_liq)
- [x] cloud cover: fraction of columns where lwp > 0
- [x] cloud top: highest z level where q_liq>0
- [x] cloud base: lowest z level where q_liq>0

### core

Profiles (t,z):

- [x] horizontal area (fraction) where q_liq > 0 and w > 0
- [x] u, v ,w, ρ, q_tot, thl, e_int conditional on q_liq > 0 and w > 0
- [x] q_tot'q_tot', thl'thl', e_int'e_int' conditional on q_liq > 0 and w > 0
- [x] u'u', v'v', w'w' conditional on q_liq > 0 and w > 0
- [x] w'ρ', w'q_tot', w'thl', w'e_int', q_tot'thl', q_tot'e_int' conditional on q_liq > 0 and w > 0

**Optimization: for all the variance and covariance (a'a' and a'b'), we can save aa and ab and a and b, as an alternative to save computation. E.g., we can save the q_tot and q_totq_tot instead of q_tot'q_tot', and w, e_int and we_int instead of w'e_int'.**

# Additional context

This is related to #214 but I decided to submit this as a separate issue because it would be good to have these LES diagnostics for the GCP runs in 1-2 weeks.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by szy21** [comment]
@akshaysridhar @yairchn @tapios feel free to add/remove/edit the diagnostics requirement.
@kpamnany would you be able to work on this? I'm happy to help if there is any confusion on the definition of these diagnostics.

**Comment by szy21** [comment]
@tapios There is a question about whether these conditional means are for elements or for nodal points. I think they should be the conditional means of nodal points, but I don't have much understanding of DG so I want to make sure with you.

**Comment by tapios** [comment]
Yes, per nodal point, and averaged horizontally (along planes of nodal points) as for other LES statistics.

**Comment by yairchn** [comment]
1. @szy21 - do you have rain in microphysics ? if so maybe rain water path as well
2. Horizontal mean of first, second and third powers of the following variables: [theta_l, qt, u, v, w]
3. Horizontal mean of the products of w with each of the following variables: [theta_l, qt, u, v, w]

**Comment by szy21** [comment]
@yairchn please check it carefully and confirm this list includes **everything** you would like to have for the GCP runs. Thanks!

**Comment by yairchn** [comment]
@szy21 I  think of is whether we should also add the internal energy  , it's variance, covariance with w and it's conditional mean on positive ql , w flag to the list. Thetal is not linearly mixed and might give us mixed results. 
Also we should keep thermodynamic covariances , qt'thetal', Eint'qt' , at least without the w,ql flag but maybe also with.

Again , to save computation consider replacing all prime products with mean of products as I explained above.

**Comment by szy21** [comment]
> @szy21 I think of is whether we should also add the internal energy , it's variance, covariance with w and it's conditional mean on positive ql , w flag to the list. Thetal is not linearly mixed and might give us mixed results.
> Also we should keep thermodynamic covariances , qt'thetal', Eint'qt' , at least without the w,ql flag but maybe also with.
I will add them to the list
> 
> Again , to save computation consider replacing all prime products with mean of products as I explained above.
I keep it as prime products to be consistent with current diagnostics. As Kiran said, this is separate because it is an optimization issue, I will talk with him.

**Comment by szy21** [comment]
@tapios I have updated the list. This may be a bit long now. For the simplicity of the code, could you please take a look and let me know if some of these diagnostics are unnecessary? Thanks!

**Comment by yairchn** [comment]
I updated the list, removed some duplicates . 
I removed some of the conditional variables , add some unconditional terms.

**Comment by tapios** [comment]
LGTM. I edited the LWP definition (include density factor). I suggest we omit all budget terms for now. They'll be good to have, but I think it'll take a bit to compile, test, and validate them.

**Comment by szy21** [comment]
@kpamnany Please see the updated list. Let me know if there is anything unclear.

Following your previous question, I organize the diagnostics into different groups. "default" and what we currently have include diagnostics we would like to have for every simulation. Other groups (right now there is only "core") include diagnostics specific to certain simulations. If you would like to test the idea of groups, you can start with this.

**Comment by szy21** [comment]
Please see #972 for suggested names and leave comments. Thanks!

**Comment by kpamnany** [comment]
Only thing left here is LWP and then changing cloud cover to use LWP instead of `q_liq`, correct @szy21?

**Comment by szy21** [comment]
@kpamnany That is correct. You don't even have to change the calculation of cloud cover, unless there is a computational reason.

**Comment by szy21** [comment]
@kpamnany LWP is still not in the diagnostics, right? Would you like to clean up this so we can close the issue? Or should I close it now and open a new one when LWP is a high priority? (As you can tell I'm just trying to close old issues:)

**Comment by kpamnany** [comment]
I think we can add it and then close this issue with that PR.
