### ISSUE TITLE
Change variable name `step` to something else

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#95]
In several places, (for example [here](https://github.com/charleskawczynski/CLIMA/blob/master/src/ClimaAtmos/Dycore/src/CLIMAAtmosDycore.jl#L39)), `step` is used as a variable name, but `step` is a Julia intrinsic function:

```
help?> step
search: step StepRange StepRangeLen CompositeException RoundNearestTiesUp InvalidStateException isconcretetype

  step(r)

  Get the step size of an AbstractRange object.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> step(1:10)
  1

  julia> step(1:2:10)
  2

  julia> step(2.5:0.3:10.9)
  0.3

  julia> step(range(2.5, stop=10.9, length=85))
  0.1
```

So, we should probably not overwriting it to avoid confusion.

**Comment by glwagner** [comment]
`iteration` is a possible alternative for such a variable.
